/* ==========================================================================
   iLand — seed catalogue
   Real categories, product names and price points observed on iland.ge.
   Prices are in GEL (₾). This file is the *factory default*; the CMS writes
   its own copy into localStorage and the storefront reads that.
   ========================================================================== */

export const SITE = {
  name: 'iLand',
  nameKa: 'აილენდი',
  legal: 'შპს აიფოუნს.ჯი',
  taxId: '204571604',
  email: 'info@iland.ge',
  phones: ['(032) 2 228080', '(032) 2 999993'],
  address: {
    ka: 'თბილისი, ვაკე, არაყიშვილის 2',
    en: 'Arakishvili St. 2, Vake, Tbilisi',
    ru: 'ул. Аракишвили 2, Ваке, Тбилиси',
  },
  hours: { ka: 'ორშ – კვი · 10:00 – 21:00', en: 'Mon – Sun · 10:00 – 21:00', ru: 'Пн – Вс · 10:00 – 21:00' },
  map: 'https://goo.gl/maps/fVLkCQ7HV9WjZ7w6A',
  social: {
    facebook: 'https://www.facebook.com/iland.ge',
    instagram: 'https://www.instagram.com/iland.ge',
    youtube: 'https://www.youtube.com/@iland.ge',
  },
};

export const CATEGORIES = [
  { id: 'iphone',      ka: 'iPhone',        en: 'iPhone',      ru: 'iPhone',        icon: 'iphone',  order: 1 },
  { id: 'ipad',        ka: 'iPad',          en: 'iPad',        ru: 'iPad',          icon: 'ipad',    order: 2 },
  { id: 'mac',         ka: 'Mac',           en: 'Mac',         ru: 'Mac',           icon: 'mac',     order: 3 },
  { id: 'watch',       ka: 'Watch',         en: 'Watch',       ru: 'Watch',         icon: 'watch',   order: 4 },
  { id: 'tv',          ka: 'TV',            en: 'TV',          ru: 'TV',            icon: 'tv',      order: 5 },
  { id: 'accessories', ka: 'აქსესუარები',   en: 'Accessories', ru: 'Аксессуары',    icon: 'acc',     order: 6 },
  { id: 'service',     ka: 'სერვისი',       en: 'Service',     ru: 'Сервис',        icon: 'service', order: 7 },
  { id: 'gifts',       ka: 'Gift Cards',    en: 'Gift Cards',  ru: 'Gift Cards',    icon: 'gift',    order: 8 },
];

export const ACCESSORY_GROUPS = [
  'Made by Apple', 'Chargers & Cables', 'Headphones', 'Home & Speakers',
  'Holders & Vlog', 'Mice & Keyboard', 'AirTag & Accessories',
  'Screen Protectors', 'Software', 'Games for Mac', 'Car Gadgets',
];

/* Colour swatches reused across products — hex is the real device finish. */
export const FINISHES = {
  naturalTitanium:  { id: 'natural-titanium',  en: 'Natural Titanium',  ka: 'ნატურალური ტიტანი',   hex: '#C2BCB2' },
  blueTitanium:     { id: 'blue-titanium',     en: 'Blue Titanium',     ka: 'ლურჯი ტიტანი',        hex: '#4E5D6C' },
  blackTitanium:    { id: 'black-titanium',    en: 'Black Titanium',    ka: 'შავი ტიტანი',         hex: '#3B3B3D' },
  whiteTitanium:    { id: 'white-titanium',    en: 'White Titanium',    ka: 'თეთრი ტიტანი',        hex: '#F0EFEA' },
  desertTitanium:   { id: 'desert-titanium',   en: 'Desert Titanium',   ka: 'უდაბნოს ტიტანი',      hex: '#BFA48F' },
  cosmicOrange:     { id: 'cosmic-orange',     en: 'Cosmic Orange',     ka: 'კოსმოსური ნარინჯი',   hex: '#D2653A' },
  deepBlue:         { id: 'deep-blue',         en: 'Deep Blue',         ka: 'ღრმა ლურჯი',          hex: '#2C3D57' },
  silver:           { id: 'silver',            en: 'Silver',            ka: 'ვერცხლისფერი',        hex: '#E3E4E5' },
  spaceBlack:       { id: 'space-black',       en: 'Space Black',       ka: 'კოსმოსური შავი',      hex: '#2E2E30' },
  midnight:         { id: 'midnight',          en: 'Midnight',          ka: 'შუაღამე',             hex: '#2A2E33' },
  starlight:        { id: 'starlight',         en: 'Starlight',         ka: 'ვარსკვლავური',        hex: '#F0E4D3' },
  skyBlue:          { id: 'sky-blue',          en: 'Sky Blue',          ka: 'ცისფერი',             hex: '#A7C4D9' },
  pink:             { id: 'pink',              en: 'Pink',              ka: 'ვარდისფერი',          hex: '#E5C6CB' },
  ultramarine:      { id: 'ultramarine',       en: 'Ultramarine',       ka: 'ულტრამარინი',         hex: '#5A6FB0' },
  teal:             { id: 'teal',              en: 'Teal',              ka: 'ზურმუხტისფერი',       hex: '#8FBEB5' },
  jetBlack:         { id: 'jet-black',         en: 'Jet Black',         ka: 'ღრმა შავი',           hex: '#1C1C1E' },
  spaceGray:        { id: 'space-gray',        en: 'Space Gray',        ka: 'კოსმოსური რუხი',      hex: '#7D7E80' },
  white:            { id: 'white',             en: 'White',             ka: 'თეთრი',               hex: '#F5F5F7' },
};

const f = (...keys) => keys.map(k => FINISHES[k]);

/* Storage tiers: [label, priceDeltaGEL] */
const S = (...pairs) => pairs.map(([size, delta]) => ({ size, delta }));

export const PRODUCTS = [
  {
    id: 'iphone-17-pro-438', featured: true, sku: 'IPHONE438', category: 'iphone', device: 'iphone',
    image: 'assets/products/p438.jpg',
    sourceId: '438',
    name: 'iPhone 17 Pro',
    price: 3199, oldPrice: 3779, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }, { size: '2TB', delta: 0 }],
    colors: [{ id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'orange', en: 'Orange', ka: 'ნარინჯისფერი', hex: '#D2653A' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'iphone-17-436', featured: true, sku: 'IPHONE436', category: 'iphone', device: 'iphone',
    image: 'assets/products/p436.jpg',
    sourceId: '436',
    name: 'iPhone 17',
    price: 2599, oldPrice: 2979, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'green', en: 'Green', ka: 'მწვანე', hex: '#5C8A6E' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-air-437', featured: true, sku: 'IPHONE437', category: 'iphone', device: 'iphone',
    image: 'assets/products/p437.png',
    sourceId: '437',
    name: 'iPhone Air',
    price: 2599, oldPrice: 2979, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-16-pro-401', featured: true, sku: 'IPHONE401', category: 'iphone', device: 'iphone',
    image: 'assets/products/p401.jpg',
    sourceId: '401',
    name: 'iPhone 16 Pro',
    price: 2279, oldPrice: 2699, condition: 'demo', badge: 'sale', stock: 0,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-16-400', featured: true, sku: 'IPHONE400', category: 'iphone', device: 'iphone',
    image: 'assets/products/p400.jpg',
    sourceId: '400',
    name: 'iPhone 16',
    price: 1999, oldPrice: 2379, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'green', en: 'Green', ka: 'მწვანე', hex: '#5C8A6E' }, { id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-15-pro-435', featured: true, sku: 'IPHONE435', category: 'iphone', device: 'iphone',
    image: 'assets/products/p435.jpg',
    sourceId: '435',
    name: 'iPhone 15 Pro',
    price: 1899, oldPrice: 2199, condition: 'demo', badge: 'sale', stock: 0,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-17e-458', featured: true, sku: 'IPHONE458', category: 'iphone', device: 'iphone',
    image: 'assets/products/p458.jpg',
    sourceId: '458',
    name: 'iPhone 17e',
    price: 1699, oldPrice: 2099, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-14-pro-447', featured: true, sku: 'IPHONE447', category: 'iphone', device: 'iphone',
    image: 'assets/products/p447.png',
    sourceId: '447',
    name: 'iPhone 14 Pro',
    price: 1649, oldPrice: 1979, condition: 'demo', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-16e-417', sku: 'IPHONE417', category: 'iphone', device: 'iphone',
    image: 'assets/products/p417.jpg',
    sourceId: '417',
    name: 'iPhone 16e',
    price: 1499, oldPrice: 1999, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'iphone-15-387', sku: 'IPHONE387', category: 'iphone', device: 'iphone',
    image: 'assets/products/p387.jpg',
    sourceId: '387',
    name: 'iPhone 15',
    price: 1369, oldPrice: 1799, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'green', en: 'Green', ka: 'მწვანე', hex: '#5C8A6E' }, { id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'yellow', en: 'Yellow', ka: 'ყვითელი', hex: '#E5C15A' }],
  },
  {
    id: 'iphone-14-454', sku: 'IPHONE454', category: 'iphone', device: 'iphone',
    image: 'assets/products/p454.png',
    sourceId: '454',
    name: 'iPhone 14',
    price: 1179, oldPrice: 1499, condition: 'demo', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'red', en: 'Red', ka: 'წითელი', hex: '#B33A3A' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'macbook-pro-395', sku: 'MACBOO395', category: 'mac', device: 'macbook',
    image: 'assets/products/p395.jpg',
    sourceId: '395',
    name: 'MacBook Pro',
    price: 7099, oldPrice: 7999, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'macbook-pro-393', sku: 'MACBOO393', category: 'mac', device: 'macbook',
    image: 'assets/products/p393.jpg',
    sourceId: '393',
    name: 'MacBook Pro',
    price: 4779, oldPrice: 5499, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'macbook-air-375', sku: 'MACBOO375', category: 'mac', device: 'macbook',
    image: 'assets/products/p375.jpg',
    sourceId: '375',
    name: 'MacBook Air',
    price: 4449, oldPrice: 4979, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'ipad-pro-452', sku: 'IPADPR452', category: 'ipad', device: 'ipad',
    image: 'assets/products/p452.jpg',
    sourceId: '452',
    name: 'iPad Pro',
    price: 3149, oldPrice: 3499, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }, { size: '2TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'ipad-pro-397', sku: 'IPADPR397', category: 'ipad', device: 'ipad',
    image: 'assets/products/p397.jpg',
    sourceId: '397',
    name: 'iPad Pro',
    price: 2799, oldPrice: 3199, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }, { size: '2TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'macbook-air-99', sku: 'MACBOO99', category: 'mac', device: 'macbook',
    image: 'assets/products/p99.jpg',
    sourceId: '99',
    name: 'MacBook Air',
    price: 2649, oldPrice: 2999, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'ultra-3-439', sku: 'ULTRA3439', category: 'watch', device: 'watch',
    image: 'assets/products/p439.jpg',
    sourceId: '439',
    name: 'Ultra 3',
    price: 2199, oldPrice: 2799, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'orange', en: 'Orange', ka: 'ნარინჯისფერი', hex: '#D2653A' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'macbook-neo-457', sku: 'MACBOO457', category: 'mac', device: 'macbook',
    image: 'assets/products/p457.jpg',
    sourceId: '457',
    name: 'MacBook Neo',
    price: 2199, oldPrice: 2599, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }, { id: 'yellow', en: 'Yellow', ka: 'ყვითელი', hex: '#E5C15A' }],
  },
  {
    id: 'ipad-air-459', sku: 'IPADAI459', category: 'ipad', device: 'ipad',
    image: 'assets/products/p459.jpg',
    sourceId: '459',
    name: 'iPad Air',
    price: 1899, oldPrice: 2199, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }],
  },
  {
    id: 'mac-pro-105', sku: 'MACPRO105', category: 'mac', device: 'macmini',
    image: 'assets/products/p105.jpg',
    sourceId: '105',
    name: 'Mac Pro',
    price: 1699, oldPrice: 2179, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '512GB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }],
  },
  {
    id: 'ipad-air-421', sku: 'IPADAI421', category: 'ipad', device: 'ipad',
    image: 'assets/products/p421.jpg',
    sourceId: '421',
    name: 'iPad Air',
    price: 1599, oldPrice: 1849, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }, { size: '1TB', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }],
  },
  {
    id: 'ultra-2-461', sku: 'ULTRA2461', category: 'watch', device: 'watch',
    image: 'assets/products/p461.jpg',
    sourceId: '461',
    name: 'Ultra 2',
    price: 1349, oldPrice: 1699, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'parrot-zik-headphones-202', sku: 'PARROT202', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p202.png',
    sourceId: '202',
    name: 'Parrot Zik Headphones',
    price: 1199, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'ipad-11-418', sku: 'IPAD11418', category: 'ipad', device: 'ipad',
    image: 'assets/products/p418.jpg',
    sourceId: '418',
    name: 'iPad 11',
    price: 1179, oldPrice: 1379, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 0 }, { size: '512GB', delta: 0 }],
    colors: [{ id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'sierrablue', en: 'Sierra Blue', ka: 'სიერას ლურჯი', hex: '#9BB5CE' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }, { id: 'yellow', en: 'Yellow', ka: 'ყვითელი', hex: '#E5C15A' }],
  },
  {
    id: 'ipad-pro-magic-keyboard-266', sku: 'IPADPR266', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    groups: ['Made by Apple', 'Mice & Keyboard'],
    image: 'assets/products/p266.png',
    sourceId: '266',
    name: 'iPad Pro Magic Keyboard',
    price: 949, oldPrice: 1199, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'series-11-441', sku: 'SERIES441', category: 'watch', device: 'watch',
    image: 'assets/products/p441.jpg',
    sourceId: '441',
    name: 'Series 11',
    price: 949, oldPrice: 1299, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'pink', en: 'Pink', ka: 'ვარდისფერი', hex: '#E5C6CB' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'apple-airpods-max-192', sku: 'APPLEA192', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    groups: ['Headphones', 'Made by Apple'],
    image: 'assets/products/p192.png',
    sourceId: '192',
    name: 'Apple Airpods Max',
    price: 749, oldPrice: 999, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'green', en: 'Green', ka: 'მწვანე', hex: '#5C8A6E' }, { id: 'orange', en: 'Orange', ka: 'ნარინჯისფერი', hex: '#D2653A' }, { id: 'purple', en: 'Purple', ka: 'იისფერი', hex: '#8E7CC3' }, { id: 'red', en: 'Red', ka: 'წითელი', hex: '#B33A3A' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'homepod-444', sku: 'HOMEPO444', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    groups: ['Home & Speakers', 'Made by Apple'],
    image: 'assets/products/p444.png',
    sourceId: '444',
    name: 'Homepod',
    price: 749, oldPrice: 1099, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }],
  },
  {
    id: 'airpods-pro-3-442', sku: 'AIRPOD442', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    groups: ['Headphones', 'Made by Apple'],
    image: 'assets/products/p442.png',
    sourceId: '442',
    name: 'Airpods Pro 3',
    price: 729, oldPrice: 969, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'beats-powerbeats-pro-2-450', sku: 'BEATSP450', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p450.png',
    sourceId: '450',
    name: 'Beats Powerbeats Pro 2',
    price: 679, oldPrice: 799, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'se-3-440', sku: 'SE3440', category: 'watch', device: 'watch',
    image: 'assets/products/p440.jpg',
    sourceId: '440',
    name: 'SE 3',
    price: 649, oldPrice: 749, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }],
  },
  {
    id: 'imac-magic-keyboard-with-touch-id-235', sku: 'IMACMA235', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    groups: ['Mice & Keyboard', 'Made by Apple'],
    image: 'assets/products/p235.png',
    sourceId: '235',
    name: 'iMac Magic Keyboard with Touch ID',
    price: 599, oldPrice: 699, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'ipad-pro-smart-keyboard-267', sku: 'IPADPR267', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    groups: ['Made by Apple', 'Mice & Keyboard'],
    image: 'assets/products/p267.png',
    sourceId: '267',
    name: 'iPad Pro Smart Keyboard',
    price: 529, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-tv-416', sku: 'APPLET416', category: 'tv', device: 'appletv',
    image: 'assets/products/p416.jpg',
    sourceId: '416',
    name: 'Apple TV',
    price: 469, oldPrice: 579, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '64GB', delta: 0 }, { size: '128GB', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'marshall-mid-bluetooth-headphones-170', sku: 'MARSHA170', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p170.png',
    sourceId: '170',
    name: 'Marshall MID Bluetooth Headphones',
    price: 399, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'airtag-family-pack-4pcs-242', sku: 'AIRTAG242', category: 'accessories', device: 'accessory',
    group: 'AirTag & Accessories',
    image: 'assets/products/p242.png',
    sourceId: '242',
    name: 'AirTag Family Pack (4pcs)',
    price: 399, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'airtag-270', sku: 'AIRTAG270', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p270.png',
    sourceId: '270',
    name: 'AirTag',
    price: 399, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-magic-mouse-2-234', sku: 'APPLEM234', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    groups: ['Mice & Keyboard', 'Made by Apple'],
    image: 'assets/products/p234.png',
    sourceId: '234',
    name: 'Apple Magic Mouse 2',
    price: 379, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-airpods-4-168', sku: 'APPLEA168', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p168.png',
    sourceId: '168',
    name: 'Apple Airpods 4',
    price: 349, oldPrice: 449, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '45w-macbook-air-charger-original-magsafe-2-257', sku: '45WMAC257', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p257.png',
    sourceId: '257',
    name: '45W MacBook Air Charger Original Magsafe 2',
    price: 349, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '60w-macbook-pro-charger-magsafe-1-258', sku: '60WMAC258', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p258.png',
    sourceId: '258',
    name: '60W MacBook Pro Charger Magsafe 1',
    price: 349, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-magic-trackpad-269', sku: 'APPLEM269', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p269.png',
    sourceId: '269',
    name: 'Apple Magic Trackpad',
    price: 279, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'homepod-mini-226', sku: 'HOMEPO226', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    groups: ['Home & Speakers', 'Made by Apple'],
    image: 'assets/products/p226.png',
    sourceId: '226',
    name: 'Homepod Mini',
    price: 269, oldPrice: 449, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'blue', en: 'Blue', ka: 'ლურჯი', hex: '#4E6E9E' }, { id: 'white', en: 'White', ka: 'თეთრი', hex: '#F5F5F7' }, { id: 'yellow', en: 'Yellow', ka: 'ყვითელი', hex: '#E5C15A' }],
  },
  {
    id: 'apple-pencil-245', sku: 'APPLEP245', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p245.png',
    sourceId: '245',
    name: 'Apple Pencil',
    price: 269, oldPrice: 349, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'usb-c-to-magsafe-3-cable-268', sku: 'USBCTO268', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p268.png',
    sourceId: '268',
    name: 'USB-C to Magsafe 3 Cable',
    price: 249, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-magic-trackpad-271', sku: 'APPLEM271', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p271.png',
    sourceId: '271',
    name: 'Apple Magic Trackpad',
    price: 249, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'portable-wireless-speaker-xtreme-223', sku: 'PORTAB223', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p223.png',
    sourceId: '223',
    name: 'Portable Wireless Speaker Xtreme',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'bluetooth-speaker-m229-225', sku: 'BLUETO225', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p225.png',
    sourceId: '225',
    name: 'Bluetooth Speaker M229',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'game-4in1-set-k90-236', sku: 'GAME4I236', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p236.png',
    sourceId: '236',
    name: 'Game 4in1 Set (K90)',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'airtag-leather-loop-244', sku: 'AIRTAG244', category: 'accessories', device: 'accessory',
    group: 'AirTag & Accessories',
    image: 'assets/products/p244.png',
    sourceId: '244',
    name: 'AirTag Leather Loop',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'beats-solo-buds-449', sku: 'BEATSS449', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p449.png',
    sourceId: '449',
    name: 'Beats Solo Buds',
    price: 199, oldPrice: 279, condition: 'new', badge: 'sale', stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'black', en: 'Black', ka: 'შავი', hex: '#1C1C1E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', hex: '#E3E4E5' }],
  },
  {
    id: 'iphone-magsafe-charger-246', sku: 'IPHONE246', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p246.png',
    sourceId: '246',
    name: 'iPhone Magsafe Charger',
    price: 179, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-earpods-lightning-connector-original-189', sku: 'APPLEE189', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p189.png',
    sourceId: '189',
    name: 'Apple Earpods Lightning Connector (Original)',
    price: 169, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-earpods-with-lightning-connector-original-263', sku: 'APPLEE263', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p263.png',
    sourceId: '263',
    name: 'Apple Earpods with Lightning Connector (Original)',
    price: 169, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '12-inch-light-holder-with-phone-holder-cxb300-218', sku: '12INCH218', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p218.png',
    sourceId: '218',
    name: '12-inch Light Holder with Phone Holder CXB300',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'remax-bluetooth-speaker-m11-224', sku: 'REMAXB224', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p224.png',
    sourceId: '224',
    name: 'Remax Bluetooth Speaker M11',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'game-4in1-set-kr-237', sku: 'GAME4I237', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p237.png',
    sourceId: '237',
    name: 'Game 4in1 Set (KR)',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'airtag-leather-key-ring-243', sku: 'AIRTAG243', category: 'accessories', device: 'accessory',
    group: 'AirTag & Accessories',
    image: 'assets/products/p243.png',
    sourceId: '243',
    name: 'AirTag Leather Key Ring',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'gold', en: 'Gold', ka: 'ოქროსფერი', hex: '#E8CFA9' }, { id: 'red', en: 'Red', ka: 'წითელი', hex: '#B33A3A' }],
  },
  {
    id: '20w-adatper-original-252', sku: '20WADA252', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p252.png',
    sourceId: '252',
    name: '20W Adatper (Original)',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '10-inch-light-holder-with-2-phone-holder-206', sku: '10INCH206', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p206.png',
    sourceId: '206',
    name: '10-inch Light Holder with 2 Phone Holder',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'gaming-mouse-robocop-g530-228', sku: 'GAMING228', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p228.png',
    sourceId: '228',
    name: 'Gaming Mouse RoboCop G530',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'airtag-241', sku: 'AIRTAG241', category: 'accessories', device: 'accessory',
    group: 'AirTag & Accessories',
    image: 'assets/products/p241.png',
    sourceId: '241',
    name: 'AirTag',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-watch-charger-259', sku: 'APPLEW259', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p259.png',
    sourceId: '259',
    name: 'Apple Watch Charger',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'best-core-magic-boost-bluetooth-speaker-220', sku: 'BESTCO220', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p220.png',
    sourceId: '220',
    name: 'Best Core Magic Boost Bluetooth Speaker',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'bluetooth-speaker-cylinder-221', sku: 'BLUETO221', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p221.png',
    sourceId: '221',
    name: 'Bluetooth Speaker Cylinder',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'usb-c-to-lightning-cable-cable-255', sku: 'USBCTO255', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p255.png',
    sourceId: '255',
    name: 'USB-C To Lightning Cable Cable',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'fonts-mega-pack-281', sku: 'FONTSM281', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p281.png',
    sourceId: '281',
    name: 'FONTS Mega Pack',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'adobe-photoshop-283', sku: 'ADOBEP283', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p283.png',
    sourceId: '283',
    name: 'ADOBE Photoshop',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'adobe-illustrator-287', sku: 'ADOBEI287', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p287.png',
    sourceId: '287',
    name: 'ADOBE Illustrator',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'motion-5-299', sku: 'MOTION299', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p299.png',
    sourceId: '299',
    name: 'Motion 5',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'movavi-video-converter-300', sku: 'MOVAVI300', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p300.png',
    sourceId: '300',
    name: 'Movavi Video Converter',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'mac-os-306', sku: 'MACOS306', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p306.png',
    sourceId: '306',
    name: 'Mac OS',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'logic-pro-x-307', sku: 'LOGICP307', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p307.png',
    sourceId: '307',
    name: 'Logic Pro X',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'cleanmymac-x-328', sku: 'CLEANM328', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p328.png',
    sourceId: '328',
    name: 'CleanMyMac X',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'dj-mix-pads-2-331', sku: 'DJMIXP331', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p331.png',
    sourceId: '331',
    name: 'DJ Mix Pads 2',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'got2b-bluetooth-speakerphone-335', sku: 'GOT2BB335', category: 'accessories', device: 'accessory',
    group: 'Car Gadgets',
    image: 'assets/products/p335.png',
    sourceId: '335',
    name: 'Got2B Bluetooth Speakerphone',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'coreldraw-291', sku: 'CORELD291', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p291.png',
    sourceId: '291',
    name: 'CorelDRAW',
    price: 89, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-magnetic-holder-for-iphone-bh17-214', sku: 'BOROFO214', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p214.png',
    sourceId: '214',
    name: 'BOROFONE Magnetic Holder for iPhone BH17',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'gaming-mouse-x7-227', sku: 'GAMING227', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p227.png',
    sourceId: '227',
    name: 'Gaming Mouse X7',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'microsoft-office-for-mac-282', sku: 'MICROS282', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p282.png',
    sourceId: '282',
    name: 'Microsoft Office for Mac',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'adobe-after-effects-286', sku: 'ADOBEA286', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p286.png',
    sourceId: '286',
    name: 'ADOBE After Effects',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'live-interior-3d-292', sku: 'LIVEIN292', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p292.png',
    sourceId: '292',
    name: 'Live Interior 3D',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'adobe-media-encoder-295', sku: 'ADOBEM295', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p295.png',
    sourceId: '295',
    name: 'ADOBE Media Encoder',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'wondershare-video-converter-301', sku: 'WONDER301', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p301.png',
    sourceId: '301',
    name: 'Wondershare Video Converter',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'mac-os-x-302', sku: 'MACOSX302', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p302.png',
    sourceId: '302',
    name: 'Mac OS X',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'screen-movie-recorder-309', sku: 'SCREEN309', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p309.png',
    sourceId: '309',
    name: 'Screen movie Recorder',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'minecraft-325', sku: 'MINECR325', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p325.png',
    sourceId: '325',
    name: 'Minecraft',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'fortnite-326', sku: 'FORTNI326', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p326.png',
    sourceId: '326',
    name: 'Fortnite',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'asphalt-airborne-8-327', sku: 'ASPHAL327', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p327.png',
    sourceId: '327',
    name: 'Asphalt Airborne 8+',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'filmora-x-330', sku: 'FILMOR330', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p330.png',
    sourceId: '330',
    name: 'Filmora X',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'giant-airpod-bluetooth-speaker-219', sku: 'GIANTA219', category: 'accessories', device: 'airpods',
    group: 'Home & Speakers',
    image: 'assets/products/p219.png',
    sourceId: '219',
    name: 'Giant Airpod Bluetooth Speaker',
    price: 69, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'waterproof-bluetooth-speaker-wave-222', sku: 'WATERP222', category: 'accessories', device: 'homepod',
    group: 'Home & Speakers',
    image: 'assets/products/p222.png',
    sourceId: '222',
    name: 'Waterproof Bluetooth Speaker WAVE',
    price: 69, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'gaming-mouse-g510-232', sku: 'GAMING232', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p232.png',
    sourceId: '232',
    name: 'Gaming Mouse G510',
    price: 69, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '5w-charger-combo-251', sku: '5WCHAR251', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p251.png',
    sourceId: '251',
    name: '5W Charger Combo',
    price: 69, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'noisehush-hands-free-speakerphone-334', sku: 'NOISEH334', category: 'accessories', device: 'accessory',
    group: 'Car Gadgets',
    image: 'assets/products/p334.png',
    sourceId: '334',
    name: 'Noisehush Hands-Free Speakerphone',
    price: 69, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'multipoint-bluetooth-speakerphone-333', sku: 'MULTIP333', category: 'accessories', device: 'accessory',
    group: 'Car Gadgets',
    image: 'assets/products/p333.png',
    sourceId: '333',
    name: 'Multipoint Bluetooth Speakerphone',
    price: 59, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-earpods-bluetooth-connect-188', sku: 'APPLEE188', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p188.png',
    sourceId: '188',
    name: 'Apple Earpods (Bluetooth Connect)',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'tripod-life-self-timer-208', sku: 'TRIPOD208', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p208.png',
    sourceId: '208',
    name: 'Tripod  Life Self Timer',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'multifunctional-selfie-stick-210', sku: 'MULTIF210', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p210.png',
    sourceId: '210',
    name: 'Multifunctional Selfie Stick',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-bicycle-and-moto-holder-for-iphone-bh34-213', sku: 'BOROFO213', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p213.png',
    sourceId: '213',
    name: 'BOROFONE Bicycle and Moto Holder for iPhone BH34',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-car-holder-for-iphone-bh3-215', sku: 'BOROFO215', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    groups: ['Holders & Vlog', 'Car Gadgets'],
    image: 'assets/products/p215.png',
    sourceId: '215',
    name: 'BOROFONE Car Holder for iPhone BH3',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'hoco-bicycle-mount-holder-for-iphone-216', sku: 'HOCOBI216', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p216.png',
    sourceId: '216',
    name: 'HOCO Bicycle Mount Holder for iPhone',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'gaming-mouse-x-229', sku: 'GAMING229', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p229.png',
    sourceId: '229',
    name: 'Gaming Mouse X',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'bluetooth-mouse-genius-nx920-230', sku: 'BLUETO230', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p230.png',
    sourceId: '230',
    name: 'Bluetooth Mouse Genius NX920',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'bluetooth-mouse-t-wolf-q2-233', sku: 'BLUETO233', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p233.png',
    sourceId: '233',
    name: 'Bluetooth Mouse T-WOLF Q2',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-ipad-adapter-253', sku: 'APPLEI253', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p253.png',
    sourceId: '253',
    name: 'Apple iPad Adapter',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-back-protector-glass-278', sku: 'IPHONE278', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p278.png',
    sourceId: '278',
    name: 'iPhone Back Protector Glass',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'adobe-audition-285', sku: 'ADOBEA285', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p285.png',
    sourceId: '285',
    name: 'ADOBE Audition',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'pixelmator-293', sku: 'PIXELM293', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p293.png',
    sourceId: '293',
    name: 'PIxelmator',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'imazing-294', sku: 'IMAZIN294', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p294.png',
    sourceId: '294',
    name: 'iMazing',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'imovie-298', sku: 'IMOVIE298', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p298.png',
    sourceId: '298',
    name: 'iMovie',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'world-of-tanks-310', sku: 'WORLDO310', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p310.png',
    sourceId: '310',
    name: 'World of Tanks',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'thief-master-thief-edition-311', sku: 'THIEFM311', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p311.png',
    sourceId: '311',
    name: 'Thief: Master Thief Edition',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'euro-truck-simulator-2-312', sku: 'EUROTR312', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p312.png',
    sourceId: '312',
    name: 'Euro Truck Simulator 2',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'dirt-3-313', sku: 'DIRT3313', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p313.png',
    sourceId: '313',
    name: 'Dirt 3',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'dead-island-314', sku: 'DEADIS314', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p314.png',
    sourceId: '314',
    name: 'Dead Island',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'the-long-dark-315', sku: 'THELON315', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p315.png',
    sourceId: '315',
    name: 'The Long Dark',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'gta-san-andreas-316', sku: 'GTASAN316', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p316.png',
    sourceId: '316',
    name: 'GTA: San Andreas',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'witcher-2-317', sku: 'WITCHE317', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p317.png',
    sourceId: '317',
    name: 'Witcher 2',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'mafia-iii-318', sku: 'MAFIAI318', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p318.png',
    sourceId: '318',
    name: 'Mafia III',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'tomb-raider-game-of-the-year-edition-319', sku: 'TOMBRA319', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p319.png',
    sourceId: '319',
    name: 'Tomb Raider: Game of The Year Edition',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'hitman-320', sku: 'HITMAN320', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p320.png',
    sourceId: '320',
    name: 'Hitman',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'simcity-complete-edition-321', sku: 'SIMCIT321', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p321.png',
    sourceId: '321',
    name: 'SimCity: Complete Edition',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'total-war-napoleon-322', sku: 'TOTALW322', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p322.png',
    sourceId: '322',
    name: 'Total War: Napoleon',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'dirt-4-323', sku: 'DIRT4323', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p323.png',
    sourceId: '323',
    name: 'Dirt 4',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'john-wick-hex-324', sku: 'JOHNWI324', category: 'accessories', device: 'accessory',
    group: 'Games for Mac',
    image: 'assets/products/p324.png',
    sourceId: '324',
    name: 'John Wick HEX',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'art-text-4-329', sku: 'ARTTEX329', category: 'accessories', device: 'accessory',
    group: 'Software',
    image: 'assets/products/p329.png',
    sourceId: '329',
    name: 'Art Text 4',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-car-charger-adapter-double-usb-with-lightning-cable-bz2-set-337', sku: 'BOROFO337', category: 'accessories', device: 'accessory',
    group: 'Car Gadgets',
    image: 'assets/products/p337.png',
    sourceId: '337',
    name: 'BOROFONE Car Charger Adapter (Double USB) with Lightning Cable (BZ2 set)',
    price: 49, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'arson-3x-usb-hub-120', sku: 'ARSON3120', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p120.png',
    sourceId: '120',
    name: 'ARSON 3x USB Hub',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'mount-holder-magnetic-car-air-vent-209', sku: 'MOUNTH209', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    groups: ['Holders & Vlog', 'Car Gadgets'],
    image: 'assets/products/p209.png',
    sourceId: '209',
    name: 'Mount Holder Magnetic Car Air Vent',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-magnetic-holder-for-iphone-bh22-211', sku: 'BOROFO211', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    groups: ['Holders & Vlog', 'Car Gadgets'],
    image: 'assets/products/p211.png',
    sourceId: '211',
    name: 'BOROFONE Magnetic Holder for iPhone BH22',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-magnetic-holder-for-iphone-bh13-212', sku: 'BOROFO212', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    groups: ['Holders & Vlog', 'Car Gadgets'],
    image: 'assets/products/p212.png',
    sourceId: '212',
    name: 'BOROFONE Magnetic Holder for iPhone BH13',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'tripod-selfie-stick-217', sku: 'TRIPOD217', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p217.png',
    sourceId: '217',
    name: 'Tripod Selfie Stick',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '5w-adapter-eu-250', sku: '5WADAP250', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p250.png',
    sourceId: '250',
    name: '5W Adapter (EU)',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'lightning-to-headphone-jack-256', sku: 'LIGHTN256', category: 'accessories', device: 'accessory',
    group: 'Made by Apple',
    image: 'assets/products/p256.png',
    sourceId: '256',
    name: 'Lightning to Headphone Jack',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-screen-protector-gatsby-276', sku: 'IPHONE276', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p276.png',
    sourceId: '276',
    name: 'iPhone Screen Protector GATSBY',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-car-charger-bz12-double-port-336', sku: 'BOROFO336', category: 'accessories', device: 'accessory',
    group: 'Car Gadgets',
    image: 'assets/products/p336.png',
    sourceId: '336',
    name: 'BOROFONE Car Charger (BZ12) Double Port',
    price: 39, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-5w-adapter-110', sku: 'APPLE5110', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p110.png',
    sourceId: '110',
    name: 'Apple 5W Adapter',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-lightning-to-3-5mm-adapter-114', sku: 'APPLEL114', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p114.png',
    sourceId: '114',
    name: 'Apple Lightning to 3.5mm Adapter',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-usb-to-lightning-cable-117', sku: 'APPLEU117', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p117.png',
    sourceId: '117',
    name: 'Apple USB To Lightning Cable',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-3-5-aux-cable-121', sku: 'BOROFO121', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p121.png',
    sourceId: '121',
    name: 'BOROFONE 3.5 AUX Cable',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-lightning-cable-128', sku: 'BOROFO128', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p128.png',
    sourceId: '128',
    name: 'BOROFONE USB to Lightning Cable',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-sub-c-cable-133', sku: 'BOROFO133', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p133.png',
    sourceId: '133',
    name: 'BOROFONE USB to SUB-C Cable',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-usb-c-cable-134', sku: 'BOROFO134', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p134.png',
    sourceId: '134',
    name: 'BOROFONE USB to USB-C Cable',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-c-to-usb-adapter-137', sku: 'BOROFO137', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p137.png',
    sourceId: '137',
    name: 'BOROFONE USB-C to USB Adapter',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'car-charger-adapter-double-usb-138', sku: 'CARCHA138', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    groups: ['Chargers & Cables', 'Car Gadgets'],
    image: 'assets/products/p138.png',
    sourceId: '138',
    name: 'Car Charger Adapter (Double USB)',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'hdmi-cable-1-8m-139', sku: 'HDMICA139', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p139.png',
    sourceId: '139',
    name: 'HDMI Cable (1.8m)',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'remax-car-charger-adapter-151', sku: 'REMAXC151', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    groups: ['Chargers & Cables', 'Car Gadgets'],
    image: 'assets/products/p151.png',
    sourceId: '151',
    name: 'REMAX Car Charger Adapter',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-earpods-on-3-5-jack-193', sku: 'APPLEE193', category: 'accessories', device: 'airpods',
    group: 'Headphones',
    image: 'assets/products/p193.png',
    sourceId: '193',
    name: 'Apple Earpods on 3.5 Jack',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'tripod-phone-holder-207', sku: 'TRIPOD207', category: 'accessories', device: 'accessory',
    group: 'Holders & Vlog',
    image: 'assets/products/p207.png',
    sourceId: '207',
    name: 'Tripod Phone Holder',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'genius-mouse-dx110-231', sku: 'GENIUS231', category: 'accessories', device: 'accessory',
    group: 'Mice & Keyboard',
    image: 'assets/products/p231.png',
    sourceId: '231',
    name: 'Genius Mouse DX110',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-gift-card-239', sku: 'APPLEG239', category: 'gifts', device: 'gift',
    image: 'assets/products/p239.jpg',
    sourceId: '239',
    name: 'Apple Gift Card',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-privacy-screen-protector-277', sku: 'IPHONE277', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p277.png',
    sourceId: '277',
    name: 'iPhone Privacy Screen Protector',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-micro-usb-cable-bx39-360', sku: 'BOROFO360', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p360.png',
    sourceId: '360',
    name: 'BOROFONE USB to Micro USB Cable (BX39)',
    price: 29, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: '3-head-fast-charging-cable-109', sku: '3HEADF109', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p109.png',
    sourceId: '109',
    name: '3 Head Fast Charging Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'apple-usb-to-30-pin-cable-116', sku: 'APPLEU116', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p116.png',
    sourceId: '116',
    name: 'Apple USB to 30-pin Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-lightning-cable-130', sku: 'BOROFO130', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p130.png',
    sourceId: '130',
    name: 'BOROFONE USB to Lightning Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-micro-usb-cable-132', sku: 'BOROFO132', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p132.png',
    sourceId: '132',
    name: 'BOROFONE USB to Micro USB Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-usb-c-cable-135', sku: 'BOROFO135', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p135.png',
    sourceId: '135',
    name: 'BOROFONE USB to USB-C Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'hoco-3-5-aux-cable-140', sku: 'HOCO35140', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p140.png',
    sourceId: '140',
    name: 'HOCO 3.5 AUX Cable',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'lightning-to-multifunction-adapter-149', sku: 'LIGHTN149', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p149.png',
    sourceId: '149',
    name: 'Lightning to Multifunction Adapter',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-screen-protector-with-airbag-272', sku: 'IPHONE272', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p272.png',
    sourceId: '272',
    name: 'iPhone Screen Protector with Airbag',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-screen-protector-10d-273', sku: 'IPHONE273', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p273.png',
    sourceId: '273',
    name: 'iPhone Screen Protector 10D',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'iphone-screen-protector-hd-275', sku: 'IPHONE275', category: 'accessories', device: 'accessory',
    group: 'Screen Protectors',
    image: 'assets/products/p275.png',
    sourceId: '275',
    name: 'iPhone Screen Protector HD+',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
  {
    id: 'borofone-usb-to-micro-usb-cable-bx54-359', sku: 'BOROFO359', category: 'accessories', device: 'accessory',
    group: 'Chargers & Cables',
    image: 'assets/products/p359.png',
    sourceId: '359',
    name: 'BOROFONE USB to Micro USB Cable (BX54)',
    price: 19, oldPrice: null, condition: 'new', badge: null, stock: 12,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'default', en: 'Standard', ka: 'სტანდარტული', hex: '#8A8F98' }],
  },
];

/* ------------------------------------------------------------------ Service */
export const SERVICES = [
  {
    id: 'screen-replacement', icon: 'screen',
    name: { ka: 'ეკრანის შეცვლა', en: 'Screen replacement', ru: 'Замена экрана' },
    desc: {
      ka: 'ორიგინალი ეკრანი, ერთი დღეში. True Tone და Face ID ინარჩუნებს მუშაობას.',
      en: 'Original display, same day. True Tone and Face ID keep working.',
      ru: 'Оригинальный дисплей за день. True Tone и Face ID сохраняются.',
    },
    from: 189, eta: { ka: '1 დღე', en: '1 day', ru: '1 день' }, warranty: 6,
  },
  {
    id: 'battery', icon: 'battery',
    name: { ka: 'ბატარეის შეცვლა', en: 'Battery replacement', ru: 'Замена аккумулятора' },
    desc: {
      ka: 'ახალი ბატარეა 100% ტევადობით და ჯანმრთელობის ჩვენებით.',
      en: 'A new cell at 100% capacity, with battery health reporting intact.',
      ru: 'Новый аккумулятор 100% ёмкости с корректным показом здоровья.',
    },
    from: 129, eta: { ka: '2 საათი', en: '2 hours', ru: '2 часа' }, warranty: 12,
  },
  {
    id: 'water-damage', icon: 'water',
    name: { ka: 'წყლის დაზიანება', en: 'Liquid damage', ru: 'Попадание жидкости' },
    desc: {
      ka: 'ულტრაბგერითი წმენდა და დაფის აღდგენა. დიაგნოსტიკა უფასოა.',
      en: 'Ultrasonic cleaning and board-level recovery. Diagnosis is free.',
      ru: 'Ультразвуковая чистка и ремонт платы. Диагностика бесплатно.',
    },
    from: 149, eta: { ka: '2–4 დღე', en: '2–4 days', ru: '2–4 дня' }, warranty: 3,
  },
  {
    id: 'data-transfer', icon: 'data',
    name: { ka: 'მონაცემების გადატანა', en: 'Data transfer', ru: 'Перенос данных' },
    desc: {
      ka: 'ძველიდან ახალ მოწყობილობაზე — უფასოდ, ყოველი ჩვენთან ნაყიდი მოწყობილობისთვის.',
      en: 'Old device to new — free with every device bought from us.',
      ru: 'Со старого устройства на новое — бесплатно при покупке у нас.',
    },
    from: 0, eta: { ka: '30 წუთი', en: '30 min', ru: '30 минут' }, warranty: 0,
  },
  {
    id: 'diagnostics', icon: 'diag',
    name: { ka: 'დიაგნოსტიკა', en: 'Diagnostics', ru: 'Диагностика' },
    desc: {
      ka: '32-პუნქტიანი შემოწმება წერილობითი დასკვნით. ყოველთვის უფასო.',
      en: 'A 32-point check with a written report. Always free.',
      ru: 'Проверка по 32 пунктам с письменным заключением. Всегда бесплатно.',
    },
    from: 0, eta: { ka: '20 წუთი', en: '20 min', ru: '20 минут' }, warranty: 0,
  },
  {
    id: 'trade-in', icon: 'tradein',
    name: { ka: 'Trade-in', en: 'Trade-in', ru: 'Trade-in' },
    desc: {
      ka: 'ჩააბარე ძველი მოწყობილობა და ფასდაკლება მიიღე ახალზე, იმავე დღეს.',
      en: 'Hand in the old device, take the discount on the new one, same day.',
      ru: 'Сдайте старое устройство и получите скидку на новое в тот же день.',
    },
    from: 0, eta: { ka: '15 წუთი', en: '15 min', ru: '15 минут' }, warranty: 0,
  },
];

/* ------------------------------------------------------------------ Banners */
export const BANNERS = [
  {
    id: 'b-17pro', active: true, order: 1,
    eyebrow: { ka: 'ახალი', en: 'New arrival', ru: 'Новинка' },
    title: { ka: 'iPhone 17 Pro', en: 'iPhone 17 Pro', ru: 'iPhone 17 Pro' },
    sub: {
      ka: 'ალუმინის უნიბოდი, A19 Pro და სამი 48MP კამერა. მარაგშია ვაკეში.',
      en: 'Aluminium unibody, A19 Pro and three 48MP cameras. In stock in Vake.',
      ru: 'Алюминиевый корпус, A19 Pro и три камеры 48 Мп. В наличии в Ваке.',
    },
    cta: { ka: 'ნახე iPhone 17 Pro', en: 'See iPhone 17 Pro', ru: 'Смотреть iPhone 17 Pro' },
    href: '#product/iphone-17-pro', product: 'iphone-17-pro',
    tone: 'orange',
  },
  {
    id: 'b-air', active: true, order: 2,
    eyebrow: { ka: '5.6 მმ', en: '5.6 mm', ru: '5,6 мм' },
    title: { ka: 'iPhone Air', en: 'iPhone Air', ru: 'iPhone Air' },
    sub: {
      ka: 'ყველაზე თხელი iPhone, რაც კი აშენებულა. 0%-იანი განვადებით.',
      en: 'The thinnest iPhone ever built. Available at 0% instalments.',
      ru: 'Самый тонкий iPhone. Доступна рассрочка 0%.',
    },
    cta: { ka: 'გაიცანი iPhone Air', en: 'Meet iPhone Air', ru: 'Знакомьтесь, iPhone Air' },
    href: '#product/iphone-air', product: 'iphone-air',
    tone: 'sky',
  },
  {
    id: 'b-service', active: true, order: 3,
    eyebrow: { ka: 'სერვისი', en: 'Service', ru: 'Сервис' },
    title: { ka: 'ეკრანი ერთ დღეში', en: 'Screen in a day', ru: 'Экран за один день' },
    sub: {
      ka: 'ორიგინალი ნაწილები, 6 თვის გარანტია, დიაგნოსტიკა უფასოდ.',
      en: 'Original parts, 6-month warranty, free diagnosis.',
      ru: 'Оригинальные детали, гарантия 6 месяцев, бесплатная диагностика.',
    },
    cta: { ka: 'სერვისზე გადასვლა', en: 'Go to Service', ru: 'Перейти в сервис' },
    href: '#service', product: null,
    tone: 'deep',
  },
];

/* ------------------------------------------------------------ Sales / promos */
export const PROMOS = [
  {
    id: 'p-autumn', active: true,
    label: { ka: 'შემოდგომის ფასდაკლება', en: 'Autumn sale', ru: 'Осенняя распродажа' },
    type: 'percent', value: 15,
    scope: 'category', target: 'mac',
    starts: '2026-07-01', ends: '2026-09-30',
    badge: { ka: '−15%', en: '−15%', ru: '−15%' },
  },
  {
    id: 'p-acc', active: true,
    label: { ka: 'აქსესუარები კომპლექტში', en: 'Accessory bundle', ru: 'Комплект аксессуаров' },
    type: 'percent', value: 20,
    scope: 'category', target: 'accessories',
    starts: '2026-07-15', ends: '2026-08-31',
    badge: { ka: '−20%', en: '−20%', ru: '−20%' },
  },
  {
    id: 'p-student', active: false,
    label: { ka: 'სტუდენტური', en: 'Student offer', ru: 'Студентам' },
    type: 'fixed', value: 200,
    scope: 'category', target: 'mac',
    starts: '2026-09-01', ends: '2026-10-15',
    badge: { ka: '−200₾', en: '−200₾', ru: '−200₾' },
  },
];

/* ------------------------------------------------- Instalment partners (GE) */
export const INSTALMENTS = [
  { id: 'tbc',    name: 'TBC',            months: [3, 6, 12, 24, 36], rate: 0,    label: '0%' },
  { id: 'bog',    name: 'Bank of Georgia',months: [3, 6, 12, 24],     rate: 0,    label: '0%' },
  { id: 'credo',  name: 'Credo',          months: [6, 12, 18],        rate: 0.02, label: '2%' },
];

export const SETTINGS = {
  currency: '₾',
  freeShippingOver: 200,
  deliveryTbilisiHours: 3,
  deliveryRegionsDays: 2,
  warrantyMonths: 12,
  returnDays: 14,
  testBanner: false,
};
