/* ==========================================================================
   NORVA — seed catalogue  (DEMO FIXTURES)

   Everything in this file is invented. The company, its address, its phone
   numbers, its staff, its customers, its prices and its stock counts are all
   fictional and exist only to make the demo clickable. Generated from a fixed
   seed so the demo looks the same on every machine.

   Dates are computed relative to load time, so the demo never ages out.
   ========================================================================== */

const DAY = 86400000;
/** ISO yyyy-mm-dd, `d` days from today. Keeps promos and orders always-current. */
const at = d => new Date(Date.now() + d * DAY).toISOString().slice(0, 10);

export const SITE = {
  name: 'NORVA',
  nameKa: 'ნორვა',
  legal: 'შპს ნორვა დიჯითალ',
  taxId: '400000000',
  email: 'hello@norva.example',
  phones: ['(032) 2 000 100', '(032) 2 000 200'],
  address: {
    ka: 'თბილისი, საბურთალო, ქარვასლის 8',
    en: '8 Karvasla St., Saburtalo, Tbilisi',
    ru: 'ул. Карвасла 8, Сабуртало, Тбилиси',
  },
  hours: { ka: 'ორშ – შაბ · 11:00 – 20:00', en: 'Mon – Sat · 11:00 – 20:00', ru: 'Пн – Сб · 11:00 – 20:00' },
  map: null,
  social: { facebook: null, instagram: null, youtube: null },
};

/* Nav order is deliberate: the highest-margin bench (Mac) leads, Audio and
   Home are their own modules rather than accessory sub-groups. */
export const CATEGORIES = [
  { id: 'mac',         ka: 'Mac',           en: 'Mac',         ru: 'Mac',        icon: 'mac',     order: 1 },
  { id: 'iphone',      ka: 'iPhone',        en: 'iPhone',      ru: 'iPhone',     icon: 'iphone',  order: 2 },
  { id: 'ipad',        ka: 'iPad',          en: 'iPad',        ru: 'iPad',       icon: 'ipad',    order: 3 },
  { id: 'audio',       ka: 'აუდიო',         en: 'Audio',       ru: 'Аудио',      icon: 'audio',   order: 4 },
  { id: 'watch',       ka: 'Watch',         en: 'Watch',       ru: 'Watch',      icon: 'watch',   order: 5 },
  { id: 'home',        ka: 'სახლი',         en: 'Home',        ru: 'Дом',        icon: 'home',    order: 6 },
  { id: 'accessories', ka: 'აქსესუარები',   en: 'Accessories', ru: 'Аксессуары', icon: 'acc',     order: 7 },
  { id: 'service',     ka: 'სახელოსნო',     en: 'Workshop',    ru: 'Мастерская', icon: 'service', order: 8 },
  { id: 'gifts',       ka: 'სასაჩუქრე',     en: 'Gift Cards',  ru: 'Подарочные', icon: 'gift',    order: 9 },
];

export const ACCESSORY_GROUPS = [
  'Power & Cables', 'Cases & Protection', 'Docks & Stands',
  'Input Devices', 'Storage & Drives', 'Tracking Tags',
  'Camera & Capture', 'Vehicle Kit',
];

/* Colour swatches reused across products. Generic hardware finishes. */
export const FINISHES = {
  graphite: { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' },
  silver: { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' },
  midnight: { id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' },
  starlight: { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' },
  slate: { id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' },
  sand: { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' },
  forest: { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' },
  rose: { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' },
  ivory: { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' },
  copper: { id: 'copper', en: 'Copper', ka: 'სპილენძისფერი', ru: 'Медный', hex: '#B5764F' },
  ink: { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' },
  steel: { id: 'steel', en: 'Steel', ka: 'ფოლადისფერი', ru: 'Стальной', hex: '#8C949C' },
  olive: { id: 'olive', en: 'Olive', ka: 'ზეთისხილისფერი', ru: 'Оливковый', hex: '#6B7052' },
  cobalt: { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' },
  ash: { id: 'ash', en: 'Ash', ka: 'ნაცრისფერი', ru: 'Пепельный', hex: '#A6A9AD' },
  bronze: { id: 'bronze', en: 'Bronze', ka: 'ბრინჯაოსფერი', ru: 'Бронзовый', hex: '#8A6A45' },
  pearl: { id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' },
  onyx: { id: 'onyx', en: 'Onyx', ka: 'ონიქსი', ru: 'Оникс', hex: '#141619' },
};

export const PRODUCTS = [
  {
    id: 'macbook-air-13-inch-m4', featured: true, sku: 'NRV-MAC-4100', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-air-13-inch-m4.svg',
    name: 'MacBook Air 13" M4',
    price: 3299, oldPrice: null, condition: 'new', badge: null, stock: 6,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 520 }, { size: '1TB', delta: 1180 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }, { id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }],
  },
  {
    id: 'macbook-air-15-inch-m4', sku: 'NRV-MAC-4107', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-air-15-inch-m4.svg',
    name: 'MacBook Air 15" M4',
    price: 3899, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 520 }, { size: '1TB', delta: 1180 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-air-13-inch-m3', sku: 'NRV-MAC-4114', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-air-13-inch-m3.svg',
    name: 'MacBook Air 13" M3',
    price: 2699, oldPrice: null, condition: 'new', badge: null, stock: 13,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 480 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-pro-14-inch-m4', sku: 'NRV-MAC-4121', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-pro-14-inch-m4.svg',
    name: 'MacBook Pro 14" M4',
    price: 5199, oldPrice: null, condition: 'new', badge: null, stock: 30,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 620 }, { size: '2TB', delta: 1640 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-pro-14-inch-m4-pro', sku: 'NRV-MAC-4128', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-pro-14-inch-m4-pro.svg',
    name: 'MacBook Pro 14" M4 Pro',
    price: 6499, oldPrice: 8190, condition: 'new', badge: 'sale', stock: 37,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 620 }, { size: '2TB', delta: 1640 }, { size: '4TB', delta: 3480 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-pro-14-inch-m3', sku: 'NRV-MAC-4135', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-pro-14-inch-m3.svg',
    name: 'MacBook Pro 14" M3',
    price: 4399, oldPrice: 5670, condition: 'open-box', badge: 'refurb', stock: 14,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 590 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-pro-16-inch-m4-pro', sku: 'NRV-MAC-4142', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-pro-16-inch-m4-pro.svg',
    name: 'MacBook Pro 16" M4 Pro',
    price: 7899, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 620 }, { size: '2TB', delta: 1640 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'macbook-pro-16-inch-m4-max', sku: 'NRV-MAC-4149', category: 'mac', device: 'laptop',
    image: 'assets/products/macbook-pro-16-inch-m4-max.svg',
    name: 'MacBook Pro 16" M4 Max',
    price: 9899, oldPrice: null, condition: 'new', badge: 'new', stock: 2,
    storage: [{ size: '1TB', delta: 0 }, { size: '2TB', delta: 1080 }, { size: '4TB', delta: 2960 }, { size: '8TB', delta: 6420 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
  },
  {
    id: 'imac-24-inch-m4', sku: 'NRV-MAC-4156', category: 'mac', device: 'desktop',
    image: 'assets/products/imac-24-inch-m4.svg',
    name: 'iMac 24" M4',
    price: 3699, oldPrice: null, condition: 'new', badge: null, stock: 27,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 480 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'mac-mini-m4', featured: true, sku: 'NRV-MAC-4163', category: 'mac', device: 'desktop',
    image: 'assets/products/mac-mini-m4.svg',
    name: 'Mac mini M4',
    price: 1899, oldPrice: 2160, condition: 'new', badge: 'sale', stock: 2,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 480 }, { size: '1TB', delta: 1090 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'mac-mini-m4-pro', sku: 'NRV-MAC-4170', category: 'mac', device: 'desktop',
    image: 'assets/products/mac-mini-m4-pro.svg',
    name: 'Mac mini M4 Pro',
    price: 3199, oldPrice: 4070, condition: 'new', badge: 'sale', stock: 28,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 610 }, { size: '2TB', delta: 1620 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'mac-studio-m4-max', sku: 'NRV-MAC-4177', category: 'mac', device: 'desktop',
    image: 'assets/products/mac-studio-m4-max.svg',
    name: 'Mac Studio M4 Max',
    price: 6899, oldPrice: null, condition: 'new', badge: null, stock: 14,
    storage: [{ size: '512GB', delta: 0 }, { size: '1TB', delta: 610 }, { size: '2TB', delta: 1620 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'mac-studio-m3-ultra', sku: 'NRV-MAC-4184', category: 'mac', device: 'desktop',
    image: 'assets/products/mac-studio-m3-ultra.svg',
    name: 'Mac Studio M3 Ultra',
    price: 9499, oldPrice: null, condition: 'new', badge: null, stock: 11,
    storage: [{ size: '1TB', delta: 0 }, { size: '2TB', delta: 1080 }, { size: '4TB', delta: 2960 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'studio-display-27-inch', sku: 'NRV-MAC-4191', category: 'mac', device: 'display',
    image: 'assets/products/studio-display-27-inch.svg',
    name: 'Studio Display 27"',
    price: 4499, oldPrice: null, condition: 'new', badge: null, stock: 29,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'iphone-17-pro-max', sku: 'NRV-PHN-4198', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-17-pro-max.svg',
    name: 'iPhone 17 Pro Max',
    price: 3549, oldPrice: 4600, condition: 'new', badge: 'sale', stock: 3,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 560 }, { size: '1TB', delta: 1140 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'copper', en: 'Copper', ka: 'სპილენძისფერი', ru: 'Медный', hex: '#B5764F' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'iphone-17-pro', featured: true, sku: 'NRV-PHN-4205', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-17-pro.svg',
    name: 'iPhone 17 Pro',
    price: 2949, oldPrice: null, condition: 'new', badge: null, stock: 4,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 560 }, { size: '1TB', delta: 1140 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'copper', en: 'Copper', ka: 'სპილენძისფერი', ru: 'Медный', hex: '#B5764F' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'iphone-17', sku: 'NRV-PHN-4212', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-17.svg',
    name: 'iPhone 17',
    price: 2249, oldPrice: 2540, condition: 'new', badge: 'sale', stock: 31,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 300 }, { size: '512GB', delta: 820 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }],
  },
  {
    id: 'iphone-air', sku: 'NRV-PHN-4219', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-air.svg',
    name: 'iPhone Air',
    price: 2649, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 540 }, { size: '1TB', delta: 1120 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }],
  },
  {
    id: 'iphone-16-pro-max', sku: 'NRV-PHN-4226', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-16-pro-max.svg',
    name: 'iPhone 16 Pro Max',
    price: 3049, oldPrice: 3820, condition: 'new', badge: 'sale', stock: 38,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 540 }, { size: '1TB', delta: 1090 }],
    colors: [{ id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'iphone-16-pro', sku: 'NRV-PHN-4233', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-16-pro.svg',
    name: 'iPhone 16 Pro',
    price: 2549, oldPrice: null, condition: 'new', badge: null, stock: 23,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 290 }, { size: '512GB', delta: 800 }],
    colors: [{ id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'iphone-16', sku: 'NRV-PHN-4240', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-16.svg',
    name: 'iPhone 16',
    price: 1949, oldPrice: null, condition: 'new', badge: 'bestseller', stock: 5,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 290 }],
    colors: [{ id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'olive', en: 'Olive', ka: 'ზეთისხილისფერი', ru: 'Оливковый', hex: '#6B7052' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'iphone-16e', sku: 'NRV-PHN-4247', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-16e.svg',
    name: 'iPhone 16e',
    price: 1449, oldPrice: 1580, condition: 'new', badge: 'sale', stock: 38,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 280 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'iphone-15-pro', sku: 'NRV-PHN-4254', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-15-pro.svg',
    name: 'iPhone 15 Pro',
    price: 2149, oldPrice: 2720, condition: 'open-box', badge: 'refurb', stock: 1,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 280 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }],
  },
  {
    id: 'iphone-15', sku: 'NRV-PHN-4261', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-15.svg',
    name: 'iPhone 15',
    price: 1649, oldPrice: null, condition: 'new', badge: null, stock: 1,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 280 }],
    colors: [{ id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }],
  },
  {
    id: 'iphone-14', sku: 'NRV-PHN-4268', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-14.svg',
    name: 'iPhone 14',
    price: 1249, oldPrice: 1570, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 270 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'iphone-se', sku: 'NRV-PHN-4275', category: 'iphone', device: 'phone',
    image: 'assets/products/iphone-se.svg',
    name: 'iPhone SE',
    price: 1099, oldPrice: null, condition: 'new', badge: null, stock: 36,
    storage: [{ size: '64GB', delta: 0 }, { size: '128GB', delta: 210 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'ipad-pro-13-inch-m4', sku: 'NRV-TAB-4282', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-pro-13-inch-m4.svg',
    name: 'iPad Pro 13" M4',
    price: 3399, oldPrice: null, condition: 'new', badge: null, stock: 2,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 520 }, { size: '1TB', delta: 1140 }, { size: '2TB', delta: 2280 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'ipad-pro-11-inch-m4', sku: 'NRV-TAB-4289', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-pro-11-inch-m4.svg',
    name: 'iPad Pro 11" M4',
    price: 2799, oldPrice: null, condition: 'new', badge: null, stock: 19,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 520 }, { size: '1TB', delta: 1140 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'ipad-air-13-inch-m3', sku: 'NRV-TAB-4296', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-air-13-inch-m3.svg',
    name: 'iPad Air 13" M3',
    price: 2149, oldPrice: null, condition: 'new', badge: null, stock: 11,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 290 }, { size: '512GB', delta: 800 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
  },
  {
    id: 'ipad-air-11-inch-m3', featured: true, sku: 'NRV-TAB-4303', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-air-11-inch-m3.svg',
    name: 'iPad Air 11" M3',
    price: 1749, oldPrice: null, condition: 'new', badge: null, stock: 5,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 290 }, { size: '512GB', delta: 800 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
  },
  {
    id: 'ipad-air-11-inch-m2', sku: 'NRV-TAB-4310', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-air-11-inch-m2.svg',
    name: 'iPad Air 11" M2',
    price: 1549, oldPrice: 1950, condition: 'open-box', badge: 'refurb', stock: 9,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 280 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'ipad-mini-a17-pro', sku: 'NRV-TAB-4317', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-mini-a17-pro.svg',
    name: 'iPad mini A17 Pro',
    price: 1449, oldPrice: 1900, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 280 }, { size: '512GB', delta: 790 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
  },
  {
    id: 'ipad-a16', sku: 'NRV-TAB-4324', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-a16.svg',
    name: 'iPad A16',
    price: 1049, oldPrice: null, condition: 'new', badge: null, stock: 39,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 270 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }],
  },
  {
    id: 'ipad-pro-13-inch-m5', sku: 'NRV-TAB-4331', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-pro-13-inch-m5.svg',
    name: 'iPad Pro 13" M5',
    price: 3899, oldPrice: null, condition: 'new', badge: 'new', stock: 36,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 540 }, { size: '1TB', delta: 1180 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'ipad-pro-11-inch-m5', sku: 'NRV-TAB-4338', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-pro-11-inch-m5.svg',
    name: 'iPad Pro 11" M5',
    price: 3199, oldPrice: null, condition: 'new', badge: 'new', stock: 27,
    storage: [{ size: '256GB', delta: 0 }, { size: '512GB', delta: 540 }, { size: '1TB', delta: 1180 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'ipad-mini-7', sku: 'NRV-TAB-4345', category: 'ipad', device: 'tablet',
    image: 'assets/products/ipad-mini-7.svg',
    name: 'iPad mini 7',
    price: 1299, oldPrice: null, condition: 'new', badge: null, stock: 6,
    storage: [{ size: '128GB', delta: 0 }, { size: '256GB', delta: 270 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'airpods-pro-3', featured: true, sku: 'NRV-AUD-4352', category: 'audio', device: 'buds',
    image: 'assets/products/airpods-pro-3.svg',
    name: 'AirPods Pro 3',
    price: 749, oldPrice: null, condition: 'new', badge: 'new', stock: 10,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'airpods-pro-2', sku: 'NRV-AUD-4359', category: 'audio', device: 'buds',
    image: 'assets/products/airpods-pro-2.svg',
    name: 'AirPods Pro 2',
    price: 599, oldPrice: 790, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'airpods-4', sku: 'NRV-AUD-4366', category: 'audio', device: 'buds',
    image: 'assets/products/airpods-4.svg',
    name: 'AirPods 4',
    price: 399, oldPrice: 450, condition: 'new', badge: 'sale', stock: 34,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'airpods-4-with-anc', sku: 'NRV-AUD-4373', category: 'audio', device: 'buds',
    image: 'assets/products/airpods-4-with-anc.svg',
    name: 'AirPods 4 with ANC',
    price: 549, oldPrice: null, condition: 'new', badge: null, stock: 15,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'airpods-max', sku: 'NRV-AUD-4380', category: 'audio', device: 'headphones',
    image: 'assets/products/airpods-max.svg',
    name: 'AirPods Max',
    price: 1349, oldPrice: null, condition: 'new', badge: null, stock: 20,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
  },
  {
    id: 'beats-studio-pro', featured: true, sku: 'NRV-AUD-4387', category: 'audio', device: 'headphones',
    image: 'assets/products/beats-studio-pro.svg',
    name: 'Beats Studio Pro',
    price: 849, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }],
  },
  {
    id: 'beats-solo-4', sku: 'NRV-AUD-4394', category: 'audio', device: 'headphones',
    image: 'assets/products/beats-solo-4.svg',
    name: 'Beats Solo 4',
    price: 449, oldPrice: 560, condition: 'open-box', badge: 'refurb', stock: 36,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }],
  },
  {
    id: 'beats-fit-pro', sku: 'NRV-AUD-4401', category: 'audio', device: 'buds',
    image: 'assets/products/beats-fit-pro.svg',
    name: 'Beats Fit Pro',
    price: 549, oldPrice: 630, condition: 'new', badge: 'sale', stock: 30,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
  },
  {
    id: 'beats-powerbeats-pro-2', sku: 'NRV-AUD-4408', category: 'audio', device: 'buds',
    image: 'assets/products/beats-powerbeats-pro-2.svg',
    name: 'Beats Powerbeats Pro 2',
    price: 799, oldPrice: null, condition: 'new', badge: null, stock: 13,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'beats-studio-buds-plus', sku: 'NRV-AUD-4415', category: 'audio', device: 'buds',
    image: 'assets/products/beats-studio-buds-plus.svg',
    name: 'Beats Studio Buds +',
    price: 429, oldPrice: null, condition: 'new', badge: null, stock: 30,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'beats-solo-buds', sku: 'NRV-AUD-4422', category: 'audio', device: 'buds',
    image: 'assets/products/beats-solo-buds.svg',
    name: 'Beats Solo Buds',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 14,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
  },
  {
    id: 'beats-pill', sku: 'NRV-AUD-4429', category: 'audio', device: 'speaker',
    image: 'assets/products/beats-pill.svg',
    name: 'Beats Pill',
    price: 379, oldPrice: null, condition: 'new', badge: null, stock: 1,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
  },
  {
    id: 'apple-watch-ultra-3', sku: 'NRV-WCH-4436', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-ultra-3.svg',
    name: 'Apple Watch Ultra 3',
    price: 2649, oldPrice: null, condition: 'new', badge: 'new', stock: 36,
    storage: [{ size: '49mm', delta: 0 }],
    colors: [{ id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'apple-watch-ultra-2', sku: 'NRV-WCH-4443', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-ultra-2.svg',
    name: 'Apple Watch Ultra 2',
    price: 2249, oldPrice: 2590, condition: 'new', badge: 'sale', stock: 20,
    storage: [{ size: '49mm', delta: 0 }],
    colors: [{ id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }],
  },
  {
    id: 'apple-watch-series-11', featured: true, sku: 'NRV-WCH-4450', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-series-11.svg',
    name: 'Apple Watch Series 11',
    price: 1249, oldPrice: null, condition: 'new', badge: null, stock: 3,
    storage: [{ size: '42mm', delta: 0 }, { size: '46mm', delta: 180 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }],
  },
  {
    id: 'apple-watch-series-11-cellular', sku: 'NRV-WCH-4457', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-series-11-cellular.svg',
    name: 'Apple Watch Series 11 Cellular',
    price: 1549, oldPrice: 1680, condition: 'new', badge: 'sale', stock: 2,
    storage: [{ size: '42mm', delta: 0 }, { size: '46mm', delta: 180 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'apple-watch-series-10', sku: 'NRV-WCH-4464', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-series-10.svg',
    name: 'Apple Watch Series 10',
    price: 1049, oldPrice: 1270, condition: 'open-box', badge: 'refurb', stock: 27,
    storage: [{ size: '42mm', delta: 0 }, { size: '46mm', delta: 170 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'apple-watch-se-3', sku: 'NRV-WCH-4471', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-se-3.svg',
    name: 'Apple Watch SE 3',
    price: 749, oldPrice: null, condition: 'new', badge: 'bestseller', stock: 35,
    storage: [{ size: '40mm', delta: 0 }, { size: '44mm', delta: 150 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'starlight', en: 'Starlight', ka: 'ვარსკვლავური', ru: 'Сияющая звезда', hex: '#EFE6D8' }],
  },
  {
    id: 'apple-watch-se-2', sku: 'NRV-WCH-4478', category: 'watch', device: 'watch',
    image: 'assets/products/apple-watch-se-2.svg',
    name: 'Apple Watch SE 2',
    price: 649, oldPrice: null, condition: 'new', badge: null, stock: 1,
    storage: [{ size: '40mm', delta: 0 }, { size: '44mm', delta: 150 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }],
  },
  {
    id: 'milanese-loop-band', sku: 'NRV-WCH-4485', category: 'watch', device: 'band',
    image: 'assets/products/milanese-loop-band.svg',
    name: 'Milanese Loop Band',
    price: 299, oldPrice: 380, condition: 'new', badge: 'sale', stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }, { id: 'bronze', en: 'Bronze', ka: 'ბრინჯაოსფერი', ru: 'Бронзовый', hex: '#8A6A45' }],
  },
  {
    id: 'sport-band', sku: 'NRV-WCH-4492', category: 'watch', device: 'band',
    image: 'assets/products/sport-band.svg',
    name: 'Sport Band',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 25,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
  },
  {
    id: 'ocean-band', sku: 'NRV-WCH-4499', category: 'watch', device: 'band',
    image: 'assets/products/ocean-band.svg',
    name: 'Ocean Band',
    price: 249, oldPrice: null, condition: 'new', badge: null, stock: 19,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }],
  },
  {
    id: 'apple-tv-4k-128gb', sku: 'NRV-HOM-4506', category: 'home', device: 'streamer',
    image: 'assets/products/apple-tv-4k-128gb.svg',
    name: 'Apple TV 4K 128GB',
    price: 549, oldPrice: null, condition: 'new', badge: null, stock: 16,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'apple-tv-4k-64gb', sku: 'NRV-HOM-4513', category: 'home', device: 'streamer',
    image: 'assets/products/apple-tv-4k-64gb.svg',
    name: 'Apple TV 4K 64GB',
    price: 449, oldPrice: null, condition: 'new', badge: null, stock: 31,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'apple-tv-4k-2022', sku: 'NRV-HOM-4520', category: 'home', device: 'streamer',
    image: 'assets/products/apple-tv-4k-2022.svg',
    name: 'Apple TV 4K (2022)',
    price: 379, oldPrice: null, condition: 'new', badge: null, stock: 39,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
  },
  {
    id: 'homepod', sku: 'NRV-HOM-4527', category: 'home', device: 'speaker',
    image: 'assets/products/homepod.svg',
    name: 'HomePod',
    price: 899, oldPrice: null, condition: 'new', badge: null, stock: 1,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }],
  },
  {
    id: 'homepod-mini', featured: true, sku: 'NRV-HOM-4534', category: 'home', device: 'speaker',
    image: 'assets/products/homepod-mini.svg',
    name: 'HomePod mini',
    price: 299, oldPrice: null, condition: 'new', badge: null, stock: 14,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }, { id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }],
  },
  {
    id: 'airtag', sku: 'NRV-HOM-4541', category: 'home', device: 'tag',
    image: 'assets/products/airtag.svg',
    name: 'AirTag',
    price: 119, oldPrice: 150, condition: 'new', badge: 'sale', stock: 40,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'airtag-4-pack', sku: 'NRV-HOM-4548', category: 'home', device: 'tag',
    image: 'assets/products/airtag-4-pack.svg',
    name: 'AirTag 4 Pack',
    price: 379, oldPrice: 430, condition: 'new', badge: 'sale', stock: 22,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
  },
  {
    id: 'siri-remote', sku: 'NRV-HOM-4555', category: 'home', device: 'remote',
    image: 'assets/products/siri-remote.svg',
    name: 'Siri Remote',
    price: 189, oldPrice: null, condition: 'new', badge: null, stock: 26,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
  },
  {
    id: 'gift-card-50gel', sku: 'NRV-GFT-4562', category: 'gifts', device: 'card',
    image: 'assets/products/gift-card-50gel.svg',
    name: 'Gift Card 50₾',
    price: 50, oldPrice: null, condition: 'new', badge: null, stock: 0,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'sand', en: 'Sand', ka: 'ქვიშისფერი', ru: 'Песочный', hex: '#C9B79E' }],
  },
  {
    id: 'gift-card-100gel', sku: 'NRV-GFT-4569', category: 'gifts', device: 'card',
    image: 'assets/products/gift-card-100gel.svg',
    name: 'Gift Card 100₾',
    price: 100, oldPrice: 130, condition: 'new', badge: 'sale', stock: 33,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'slate', en: 'Slate Blue', ka: 'ლურჯი შიფერი', ru: 'Синий сланец', hex: '#4A5A6E' }],
  },
  {
    id: 'gift-card-250gel', sku: 'NRV-GFT-4576', category: 'gifts', device: 'card',
    image: 'assets/products/gift-card-250gel.svg',
    name: 'Gift Card 250₾',
    price: 250, oldPrice: null, condition: 'new', badge: null, stock: 18,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'forest', en: 'Forest', ka: 'მუქი მწვანე', ru: 'Тёмно-зелёный', hex: '#3E5348' }],
  },
  {
    id: '20w-usb-c-power-adapter', sku: 'NRV-ACC-4583', category: 'accessories', device: 'psu',
    image: 'assets/products/20w-usb-c-power-adapter.svg',
    name: '20W USB-C Power Adapter',
    price: 65, oldPrice: 80, condition: 'new', badge: 'sale', stock: 16,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: '35w-dual-usb-c-power-adapter', sku: 'NRV-ACC-4590', category: 'accessories', device: 'psu',
    image: 'assets/products/35w-dual-usb-c-power-adapter.svg',
    name: '35W Dual USB-C Power Adapter',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 24,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: '70w-usb-c-power-adapter', sku: 'NRV-ACC-4597', category: 'accessories', device: 'psu',
    image: 'assets/products/70w-usb-c-power-adapter.svg',
    name: '70W USB-C Power Adapter',
    price: 179, oldPrice: 240, condition: 'new', badge: 'sale', stock: 36,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: 'usb-c-to-lightning-cable-1-m', sku: 'NRV-ACC-4604', category: 'accessories', device: 'cable',
    image: 'assets/products/usb-c-to-lightning-cable-1-m.svg',
    name: 'USB-C to Lightning Cable (1 m)',
    price: 75, oldPrice: null, condition: 'new', badge: null, stock: 32,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: 'usb-c-charge-cable-2-m', sku: 'NRV-ACC-4611', category: 'accessories', device: 'cable',
    image: 'assets/products/usb-c-charge-cable-2-m.svg',
    name: 'USB-C Charge Cable (2 m)',
    price: 89, oldPrice: null, condition: 'new', badge: null, stock: 6,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Power & Cables',
  },
  {
    id: 'magsafe-3-cable-2-m', sku: 'NRV-ACC-4618', category: 'accessories', device: 'cable',
    image: 'assets/products/magsafe-3-cable-2-m.svg',
    name: 'MagSafe 3 Cable (2 m)',
    price: 145, oldPrice: 160, condition: 'new', badge: 'sale', stock: 6,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: 'magsafe-charger-2nd-generation', sku: 'NRV-ACC-4625', category: 'accessories', device: 'puck',
    image: 'assets/products/magsafe-charger-2nd-generation.svg',
    name: 'MagSafe Charger (2nd generation)',
    price: 155, oldPrice: null, condition: 'new', badge: 'bestseller', stock: 7,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Power & Cables',
  },
  {
    id: 'usb-c-to-usb-c-braided-charge-cable-with-magsafe-travel-adapter-and-zip-pouch-2-m-midnight', sku: 'NRV-ACC-4632', category: 'accessories', device: 'cable',
    image: 'assets/products/usb-c-to-usb-c-braided-charge-cable-with-magsafe-travel-adapter-and-zip-pouch-2-m-midnight.svg',
    name: 'USB-C to USB-C Braided Charge Cable with MagSafe Travel Adapter and Zip Pouch (2 m, Midnight)',
    price: 219, oldPrice: 250, condition: 'new', badge: 'sale', stock: 2,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'midnight', en: 'Midnight', ka: 'შუაღამე', ru: 'Тёмная ночь', hex: '#23272E' }],
    group: 'Power & Cables',
  },
  {
    id: 'silicone-case-with-magsafe', sku: 'NRV-ACC-4639', category: 'accessories', device: 'case',
    image: 'assets/products/silicone-case-with-magsafe.svg',
    name: 'Silicone Case with MagSafe',
    price: 159, oldPrice: 200, condition: 'new', badge: 'sale', stock: 26,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }, { id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'olive', en: 'Olive', ka: 'ზეთისხილისფერი', ru: 'Оливковый', hex: '#6B7052' }],
    group: 'Cases & Protection',
  },
  {
    id: 'clear-case-with-magsafe', sku: 'NRV-ACC-4646', category: 'accessories', device: 'case',
    image: 'assets/products/clear-case-with-magsafe.svg',
    name: 'Clear Case with MagSafe',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 9,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }],
    group: 'Cases & Protection',
  },
  {
    id: 'woven-wallet-with-magsafe', sku: 'NRV-ACC-4653', category: 'accessories', device: 'case',
    image: 'assets/products/woven-wallet-with-magsafe.svg',
    name: 'Woven Wallet with MagSafe',
    price: 199, oldPrice: null, condition: 'new', badge: null, stock: 10,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'bronze', en: 'Bronze', ka: 'ბრინჯაოსფერი', ru: 'Бронзовый', hex: '#8A6A45' }],
    group: 'Cases & Protection',
  },
  {
    id: 'privacy-screen-protector', sku: 'NRV-ACC-4660', category: 'accessories', device: 'glass',
    image: 'assets/products/privacy-screen-protector.svg',
    name: 'Privacy Screen Protector',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 9,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Cases & Protection',
  },
  {
    id: 'ceramic-screen-protector', sku: 'NRV-ACC-4667', category: 'accessories', device: 'glass',
    image: 'assets/products/ceramic-screen-protector.svg',
    name: 'Ceramic Screen Protector',
    price: 59, oldPrice: null, condition: 'new', badge: null, stock: 4,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }],
    group: 'Cases & Protection',
  },
  {
    id: 'camera-lens-protector', sku: 'NRV-ACC-4674', category: 'accessories', device: 'glass',
    image: 'assets/products/camera-lens-protector.svg',
    name: 'Camera Lens Protector',
    price: 45, oldPrice: 50, condition: 'new', badge: 'sale', stock: 22,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Cases & Protection',
  },
  {
    id: 'magsafe-duo-charger', sku: 'NRV-ACC-4681', category: 'accessories', device: 'puck',
    image: 'assets/products/magsafe-duo-charger.svg',
    name: 'MagSafe Duo Charger',
    price: 289, oldPrice: null, condition: 'new', badge: null, stock: 4,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Docks & Stands',
  },
  {
    id: 'aluminium-laptop-stand', sku: 'NRV-ACC-4688', category: 'accessories', device: 'stand',
    image: 'assets/products/aluminium-laptop-stand.svg',
    name: 'Aluminium Laptop Stand',
    price: 179, oldPrice: null, condition: 'new', badge: null, stock: 1,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Docks & Stands',
  },
  {
    id: 'desk-dock-for-iphone', sku: 'NRV-ACC-4695', category: 'accessories', device: 'stand',
    image: 'assets/products/desk-dock-for-iphone.svg',
    name: 'Desk Dock for iPhone',
    price: 219, oldPrice: 260, condition: 'new', badge: 'sale', stock: 35,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Docks & Stands',
  },
  {
    id: 'single-monitor-arm', sku: 'NRV-ACC-4702', category: 'accessories', device: 'stand',
    image: 'assets/products/single-monitor-arm.svg',
    name: 'Single Monitor Arm',
    price: 349, oldPrice: null, condition: 'new', badge: null, stock: 30,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Docks & Stands',
  },
  {
    id: '3-in-1-charging-station', sku: 'NRV-ACC-4709', category: 'accessories', device: 'puck',
    image: 'assets/products/3-in-1-charging-station.svg',
    name: '3-in-1 Charging Station',
    price: 399, oldPrice: null, condition: 'new', badge: null, stock: 29,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }, { id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Docks & Stands',
  },
  {
    id: 'magic-keyboard-with-touch-id', sku: 'NRV-ACC-4716', category: 'accessories', device: 'keyboard',
    image: 'assets/products/magic-keyboard-with-touch-id.svg',
    name: 'Magic Keyboard with Touch ID',
    price: 599, oldPrice: null, condition: 'new', badge: null, stock: 22,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Input Devices',
  },
  {
    id: 'magic-keyboard-with-numeric-keypad', sku: 'NRV-ACC-4723', category: 'accessories', device: 'keyboard',
    image: 'assets/products/magic-keyboard-with-numeric-keypad.svg',
    name: 'Magic Keyboard with Numeric Keypad',
    price: 449, oldPrice: null, condition: 'new', badge: null, stock: 35,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }],
    group: 'Input Devices',
  },
  {
    id: 'magic-mouse-usb-c', sku: 'NRV-ACC-4730', category: 'accessories', device: 'mouse',
    image: 'assets/products/magic-mouse-usb-c.svg',
    name: 'Magic Mouse (USB-C)',
    price: 349, oldPrice: 400, condition: 'new', badge: 'sale', stock: 26,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Input Devices',
  },
  {
    id: 'magic-trackpad-usb-c', sku: 'NRV-ACC-4737', category: 'accessories', device: 'trackpad',
    image: 'assets/products/magic-trackpad-usb-c.svg',
    name: 'Magic Trackpad (USB-C)',
    price: 449, oldPrice: null, condition: 'new', badge: null, stock: 2,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Input Devices',
  },
  {
    id: 'apple-pencil-pro', sku: 'NRV-ACC-4744', category: 'accessories', device: 'pencil',
    image: 'assets/products/apple-pencil-pro.svg',
    name: 'Apple Pencil Pro',
    price: 349, oldPrice: null, condition: 'new', badge: null, stock: 15,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }],
    group: 'Input Devices',
  },
  {
    id: 'apple-pencil-usb-c', sku: 'NRV-ACC-4751', category: 'accessories', device: 'pencil',
    image: 'assets/products/apple-pencil-usb-c.svg',
    name: 'Apple Pencil (USB-C)',
    price: 229, oldPrice: null, condition: 'new', badge: null, stock: 34,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'pearl', en: 'Pearl', ka: 'მარგალიტისფერი', ru: 'Жемчужный', hex: '#E8E9EC' }],
    group: 'Input Devices',
  },
  {
    id: 'portable-ssd-1tb', sku: 'NRV-ACC-4758', category: 'accessories', device: 'drive',
    image: 'assets/products/portable-ssd-1tb.svg',
    name: 'Portable SSD 1TB',
    price: 429, oldPrice: null, condition: 'new', badge: null, stock: 8,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Storage & Drives',
  },
  {
    id: 'portable-ssd-2tb', sku: 'NRV-ACC-4765', category: 'accessories', device: 'drive',
    image: 'assets/products/portable-ssd-2tb.svg',
    name: 'Portable SSD 2TB',
    price: 749, oldPrice: null, condition: 'new', badge: null, stock: 33,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Storage & Drives',
  },
  {
    id: 'sd-card-reader-usb-c', sku: 'NRV-ACC-4772', category: 'accessories', device: 'dongle',
    image: 'assets/products/sd-card-reader-usb-c.svg',
    name: 'SD Card Reader (USB-C)',
    price: 119, oldPrice: 150, condition: 'new', badge: 'sale', stock: 37,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
    group: 'Storage & Drives',
  },
  {
    id: '7-in-1-usb-c-hub', sku: 'NRV-ACC-4779', category: 'accessories', device: 'dongle',
    image: 'assets/products/7-in-1-usb-c-hub.svg',
    name: '7-in-1 USB-C Hub',
    price: 189, oldPrice: null, condition: 'new', badge: null, stock: 29,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }, { id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Storage & Drives',
  },
  {
    id: 'thunderbolt-4-dock', sku: 'NRV-ACC-4786', category: 'accessories', device: 'drive',
    image: 'assets/products/thunderbolt-4-dock.svg',
    name: 'Thunderbolt 4 Dock',
    price: 649, oldPrice: 750, condition: 'new', badge: 'sale', stock: 21,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Storage & Drives',
  },
  {
    id: 'airtag-leather-key-ring', sku: 'NRV-ACC-4793', category: 'accessories', device: 'tag',
    image: 'assets/products/airtag-leather-key-ring.svg',
    name: 'AirTag Leather Key Ring',
    price: 149, oldPrice: null, condition: 'new', badge: null, stock: 14,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'bronze', en: 'Bronze', ka: 'ბრინჯაოსფერი', ru: 'Бронзовый', hex: '#8A6A45' }, { id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Tracking Tags',
  },
  {
    id: 'airtag-loop', sku: 'NRV-ACC-4800', category: 'accessories', device: 'tag',
    image: 'assets/products/airtag-loop.svg',
    name: 'AirTag Loop',
    price: 129, oldPrice: null, condition: 'new', badge: null, stock: 30,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'cobalt', en: 'Cobalt', ka: 'კობალტი', ru: 'Кобальт', hex: '#33518C' }, { id: 'rose', en: 'Rose', ka: 'ვარდისფერი', ru: 'Розовый', hex: '#DDB9B6' }],
    group: 'Tracking Tags',
  },
  {
    id: 'airtag-holder-2-pack', sku: 'NRV-ACC-4807', category: 'accessories', device: 'tag',
    image: 'assets/products/airtag-holder-2-pack.svg',
    name: 'AirTag Holder (2 pack)',
    price: 89, oldPrice: null, condition: 'new', badge: null, stock: 3,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Tracking Tags',
  },
  {
    id: 'wallet-finder-card', sku: 'NRV-ACC-4814', category: 'accessories', device: 'tag',
    image: 'assets/products/wallet-finder-card.svg',
    name: 'Wallet Finder Card',
    price: 99, oldPrice: null, condition: 'new', badge: null, stock: 7,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Tracking Tags',
  },
  {
    id: 'tripod-with-phone-mount', sku: 'NRV-ACC-4821', category: 'accessories', device: 'stand',
    image: 'assets/products/tripod-with-phone-mount.svg',
    name: 'Tripod with Phone Mount',
    price: 169, oldPrice: 190, condition: 'new', badge: 'sale', stock: 17,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Camera & Capture',
  },
  {
    id: '12-inch-ring-light', sku: 'NRV-ACC-4828', category: 'accessories', device: 'light',
    image: 'assets/products/12-inch-ring-light.svg',
    name: '12" Ring Light',
    price: 229, oldPrice: 280, condition: 'new', badge: 'sale', stock: 39,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ivory', en: 'Ivory', ka: 'სპილოსძვლისფერი', ru: 'Слоновая кость', hex: '#F2EEE6' }],
    group: 'Camera & Capture',
  },
  {
    id: 'lavalier-microphone-usb-c', sku: 'NRV-ACC-4835', category: 'accessories', device: 'mic',
    image: 'assets/products/lavalier-microphone-usb-c.svg',
    name: 'Lavalier Microphone (USB-C)',
    price: 189, oldPrice: 210, condition: 'new', badge: 'sale', stock: 38,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Camera & Capture',
  },
  {
    id: 'gimbal-stabiliser', sku: 'NRV-ACC-4842', category: 'accessories', device: 'stand',
    image: 'assets/products/gimbal-stabiliser.svg',
    name: 'Gimbal Stabiliser',
    price: 549, oldPrice: null, condition: 'new', badge: null, stock: 31,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Camera & Capture',
  },
  {
    id: 'action-mount-kit', sku: 'NRV-ACC-4849', category: 'accessories', device: 'stand',
    image: 'assets/products/action-mount-kit.svg',
    name: 'Action Mount Kit',
    price: 139, oldPrice: null, condition: 'new', badge: null, stock: 26,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Camera & Capture',
  },
  {
    id: 'car-vent-magnetic-mount', sku: 'NRV-ACC-4856', category: 'accessories', device: 'mount',
    image: 'assets/products/car-vent-magnetic-mount.svg',
    name: 'Car Vent Magnetic Mount',
    price: 89, oldPrice: null, condition: 'new', badge: null, stock: 32,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'graphite', en: 'Graphite', ka: 'გრაფიტი', ru: 'Графит', hex: '#3A3D42' }],
    group: 'Vehicle Kit',
  },
  {
    id: 'dual-usb-c-car-charger', sku: 'NRV-ACC-4863', category: 'accessories', device: 'psu',
    image: 'assets/products/dual-usb-c-car-charger.svg',
    name: 'Dual USB-C Car Charger',
    price: 79, oldPrice: null, condition: 'new', badge: null, stock: 35,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'silver', en: 'Silver', ka: 'ვერცხლისფერი', ru: 'Серебристый', hex: '#DCDEE1' }],
    group: 'Vehicle Kit',
  },
  {
    id: 'wireless-car-charger-mount', sku: 'NRV-ACC-4870', category: 'accessories', device: 'mount',
    image: 'assets/products/wireless-car-charger-mount.svg',
    name: 'Wireless Car Charger Mount',
    price: 189, oldPrice: 230, condition: 'new', badge: 'sale', stock: 18,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Vehicle Kit',
  },
  {
    id: 'bluetooth-car-speakerphone', sku: 'NRV-ACC-4877', category: 'accessories', device: 'speaker',
    image: 'assets/products/bluetooth-car-speakerphone.svg',
    name: 'Bluetooth Car Speakerphone',
    price: 149, oldPrice: 170, condition: 'new', badge: 'sale', stock: 30,
    storage: [{ size: '—', delta: 0 }],
    colors: [{ id: 'ink', en: 'Ink', ka: 'მელნისფერი', ru: 'Чернильный', hex: '#1E2229' }],
    group: 'Vehicle Kit',
  },
];

export const SERVICES = [
  {
    id: 'display-swap', icon: 'screen',
    name: { ka: 'ეკრანის შეცვლა', en: 'Display swap', ru: 'Замена дисплея' },
    desc: {
      ka: 'ლაბორატორიაში დალუქული ეკრანი, კალიბრაციით. ფერის პროფილი და სენსორები რჩება.',
      en: 'A sealed display fitted in the lab and recalibrated. Colour profile and sensors stay intact.',
      ru: 'Запечатанный дисплей, установка и калибровка. Цветовой профиль и датчики сохраняются.',
    },
    from: 245, eta: { ka: '4 საათი', en: '4 hours', ru: '4 часа' }, warranty: 9,
  },
  {
    id: 'cell-swap', icon: 'battery',
    name: { ka: 'ელემენტის შეცვლა', en: 'Cell replacement', ru: 'Замена элемента питания' },
    desc: {
      ka: 'ახალი ელემენტი ციკლების ნულიდან და ჯანმრთელობის სწორი ჩვენებით.',
      en: 'A fresh cell from zero cycles, with health reporting reading correctly.',
      ru: 'Новый элемент с нуля циклов и корректным показом состояния.',
    },
    from: 165, eta: { ka: '90 წუთი', en: '90 min', ru: '90 минут' }, warranty: 18,
  },
  {
    id: 'board-recovery', icon: 'water',
    name: { ka: 'დაფის აღდგენა', en: 'Board recovery', ru: 'Восстановление платы' },
    desc: {
      ka: 'ულტრაბგერითი აბაზანა და კომპონენტის დონის შედუღება. დასკვნა წერილობით.',
      en: 'Ultrasonic bath and component-level rework. The findings come in writing.',
      ru: 'Ультразвуковая ванна и пайка на уровне компонентов. Заключение письменно.',
    },
    from: 195, eta: { ka: '3–5 დღე', en: '3–5 days', ru: '3–5 дней' }, warranty: 4,
  },
  {
    id: 'migration', icon: 'data',
    name: { ka: 'მიგრაცია', en: 'Migration', ru: 'Миграция' },
    desc: {
      ka: 'ძველიდან ახალზე, თქვენს თანდასწრებით. ჩვენთან ნაყიდზე უფასოა.',
      en: 'Old device to new, while you watch. Free on anything bought here.',
      ru: 'Со старого на новое, при вас. Бесплатно для купленного у нас.',
    },
    from: 0, eta: { ka: '40 წუთი', en: '40 min', ru: '40 минут' }, warranty: 0,
  },
  {
    id: 'bench-check', icon: 'diag',
    name: { ka: 'სტენდის შემოწმება', en: 'Bench check', ru: 'Стендовая проверка' },
    desc: {
      ka: '41-პუნქტიანი შემოწმება სტენდზე. ანგარიში ყოველთვის უფასოა.',
      en: 'A 41-point run on the bench. The report is always free.',
      ru: 'Проверка по 41 пункту на стенде. Отчёт всегда бесплатный.',
    },
    from: 0, eta: { ka: '25 წუთი', en: '25 min', ru: '25 минут' }, warranty: 0,
  },
  {
    id: 'buyback', icon: 'tradein',
    name: { ka: 'გამოსყიდვა', en: 'Buy-back', ru: 'Выкуп' },
    desc: {
      ka: 'შეაფასე ძველი მოწყობილობა და ჩათვალე ახლის ფასში, იმავე ვიზიტზე.',
      en: 'Value the old device and put it against the new one on the same visit.',
      ru: 'Оценим старое устройство и зачтём в счёт нового в тот же визит.',
    },
    from: 0, eta: { ka: '20 წუთი', en: '20 min', ru: '20 минут' }, warranty: 0,
  },
];

/* ------------------------------------------------------------------ Banners */
export const BANNERS = [
  {
    id: 'b-studio', active: true, order: 1,
    eyebrow: { ka: 'სახელოსნოდან', en: 'From the bench', ru: 'Из мастерской' },
    title: { ka: 'Mac Studio M4 Max', en: 'Mac Studio M4 Max', ru: 'Mac Studio M4 Max' },
    sub: {
      ka: 'აწყობილი, განახლებული და გატესტილი მიტანამდე. ხუთწლიანი მომსახურების გეგმა კომპლექტში.',
      en: 'Built, updated and bench-tested before it leaves us. Five-year service plan included.',
      ru: 'Собран, обновлён и проверен на стенде до выдачи. Пятилетний план обслуживания включён.',
    },
    cta: { ka: 'ნახე Mac Studio', en: 'See Mac Studio', ru: 'Смотреть Mac Studio' },
    href: '#/product/mac-studio-m4-max', product: 'mac-studio-m4-max',
    tone: 'orange',
  },
  {
    id: 'b-air', active: true, order: 2,
    eyebrow: { ka: '1.24 კგ', en: '1.24 kg', ru: '1,24 кг' },
    title: { ka: 'MacBook Air 13" M4', en: 'MacBook Air 13" M4', ru: 'MacBook Air 13" M4' },
    sub: {
      ka: 'მთელი დღის ბატარეა და უხმო კორპუსი. განვადება ექვს თვემდე თანაბრად.',
      en: 'All-day battery in a silent chassis. Split it over six months, evenly.',
      ru: 'Батарея на весь день в бесшумном корпусе. Рассрочка на шесть месяцев ровными частями.',
    },
    cta: { ka: 'გაიცანი MacBook Air', en: 'Meet MacBook Air', ru: 'Знакомьтесь, MacBook Air' },
    href: '#/product/macbook-air-13-inch-m4', product: 'macbook-air-13-inch-m4',
    tone: 'sky',
  },
  {
    id: 'b-bench', active: true, order: 3,
    eyebrow: { ka: 'სახელოსნო', en: 'Workshop', ru: 'Мастерская' },
    title: { ka: 'ეკრანი ოთხ საათში', en: 'Display in four hours', ru: 'Дисплей за четыре часа' },
    sub: {
      ka: 'დალუქული ნაწილები, 9 თვის გარანტია, სტენდის შემოწმება უფასოდ.',
      en: 'Sealed parts, nine-month warranty, bench check on the house.',
      ru: 'Запечатанные детали, гарантия 9 месяцев, стендовая проверка бесплатно.',
    },
    cta: { ka: 'სახელოსნოში გადასვლა', en: 'Go to the Workshop', ru: 'Перейти в мастерскую' },
    href: '#/service', product: null,
    tone: 'deep',
  },
];

/* ------------------------------------------------------------ Sales / promos
   Windows are relative to load time, so a promo is always live and the deals
   rail on the home page never silently empties. */
export const PROMOS = [
  {
    id: 'p-bench', active: true,
    label: { ka: 'სახელოსნოს კვირა', en: 'Workshop week', ru: 'Неделя мастерской' },
    type: 'percent', value: 12,
    scope: 'category', target: 'mac',
    starts: at(-21), ends: at(28),
    badge: { ka: '−12%', en: '−12%', ru: '−12%' },
  },
  {
    id: 'p-audio', active: true,
    label: { ka: 'აუდიო კომპლექტი', en: 'Audio bundle', ru: 'Аудиокомплект' },
    type: 'percent', value: 18,
    scope: 'category', target: 'audio',
    starts: at(-7), ends: at(14),
    badge: { ka: '−18%', en: '−18%', ru: '−18%' },
  },
  {
    id: 'p-carry', active: false,
    label: { ka: 'აქსესუარები ნაკრებში', en: 'Carry kit', ru: 'Набор аксессуаров' },
    type: 'fixed', value: 40,
    scope: 'category', target: 'accessories',
    starts: at(3), ends: at(31),
    badge: { ka: '−40₾', en: '−40₾', ru: '−40₾' },
  },
];

/* --------------------------------------------------- Instalment partners
   Fictional lenders on fictional terms. The calculator is indicative only. */
export const INSTALMENTS = [
  { id: 'anda',   name: 'Anda Finance',  months: [4, 8, 16, 32], rate: 0,     label: '0%' },
  { id: 'lome',   name: 'Lome Credit',   months: [6, 18, 30],    rate: 0,     label: '0%' },
  { id: 'verta',  name: 'Verta Pay',     months: [9, 21],        rate: 0.035, label: '3.5%' },
];

export const SETTINGS = {
  currency: '₾',
  freeShippingOver: 250,
  deliveryTbilisiHours: 4,
  deliveryRegionsDays: 3,
  warrantyMonths: 24,
  returnDays: 21,
  testBanner: false,
};

/* ---------------------------------------------------------------- Orders
   Fictional customers, fictional order numbers. Day offsets are resolved at
   load time so the dashboard always has orders today and a live 7-day trend. */
export const ORDERS = [
  { id: '2140', customer: 'ე. ჩხაიძე', product: 'apple-pencil-pro', qty: 2, total: 698, status: 'packing', date: at(0) },
  { id: '2139', customer: 'D. Alania', product: 'apple-tv-4k-64gb', qty: 1, total: 449, status: 'packing', date: at(0) },
  { id: '2138', customer: 'თ. ბოლქვაძე', product: 'iphone-15', qty: 2, total: 3298, status: 'new', date: at(0) },
  { id: '2137', customer: 'N. Sikharulidze', product: 'ipad-air-11-inch-m2', qty: 1, total: 1549, status: 'packing', date: at(-1) },
  { id: '2136', customer: 'ი. ღვინიაშვილი', product: 'mac-studio-m4-max', qty: 1, total: 6899, status: 'packing', date: at(-1) },
  { id: '2135', customer: 'R. Meparishvili', product: 'usb-c-to-usb-c-braided-charge-cable-with-magsafe-travel-adapter-and-zip-pouch-2-m-midnight', qty: 1, total: 219, status: 'shipped', date: at(-1) },
  { id: '2134', customer: 'ქ. ლომსაძე', product: 'apple-watch-se-2', qty: 1, total: 649, status: 'packing', date: at(-1) },
  { id: '2133', customer: 'A. Dzneladze', product: 'bluetooth-car-speakerphone', qty: 1, total: 149, status: 'packing', date: at(-2) },
  { id: '2132', customer: 'გ. ჭანტურია', product: 'apple-watch-series-11-cellular', qty: 1, total: 1549, status: 'new', date: at(-2) },
  { id: '2131', customer: 'V. Okriashvili', product: '12-inch-ring-light', qty: 1, total: 229, status: 'new', date: at(-2) },
  { id: '2130', customer: 'მ. ტაბატაძე', product: 'wireless-car-charger-mount', qty: 1, total: 189, status: 'done', date: at(-3) },
  { id: '2129', customer: 'S. Kordzaia', product: 'airtag', qty: 1, total: 119, status: 'done', date: at(-3) },
  { id: '2128', customer: 'ლ. ბერუაშვილი', product: 'magsafe-charger-2nd-generation', qty: 1, total: 155, status: 'cancelled', date: at(-3) },
  { id: '2127', customer: 'K. Shanidze', product: 'ipad-mini-7', qty: 2, total: 2598, status: 'done', date: at(-3) },
  { id: '2126', customer: 'ო. ფხალაძე', product: 'sd-card-reader-usb-c', qty: 1, total: 119, status: 'done', date: at(-3) },
  { id: '2125', customer: 'T. Gogichaishvili', product: 'beats-solo-buds', qty: 1, total: 199, status: 'done', date: at(-4) },
  { id: '2124', customer: 'ნ. მარგველაშვილი', product: 'iphone-17-pro-max', qty: 1, total: 3549, status: 'cancelled', date: at(-4) },
  { id: '2123', customer: 'B. Ratiani', product: '70w-usb-c-power-adapter', qty: 1, total: 179, status: 'done', date: at(-5) },
  { id: '2122', customer: 'ს. ქებურია', product: 'airtag-loop', qty: 1, total: 129, status: 'done', date: at(-5) },
  { id: '2121', customer: 'E. Tvaladze', product: 'iphone-16', qty: 1, total: 1949, status: 'done', date: at(-5) },
  { id: '2120', customer: 'დ. წიკლაური', product: 'mac-studio-m3-ultra', qty: 1, total: 9499, status: 'shipped', date: at(-6) },
  { id: '2119', customer: 'M. Kapanadze', product: 'clear-case-with-magsafe', qty: 1, total: 149, status: 'shipped', date: at(-6) },
  { id: '2118', customer: 'ზ. ხარაიშვილი', product: 'magsafe-duo-charger', qty: 1, total: 289, status: 'cancelled', date: at(-7) },
  { id: '2117', customer: 'L. Datukishvili', product: 'iphone-se', qty: 1, total: 1099, status: 'done', date: at(-9) },
];
